<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Solutions | R for Conditional Process Analysis</title>
  <meta name="description" content="Using Conditional Process Analysis to evaluate communication theories - B.A. Seminar at IKMZ, FS 2022" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Solutions | R for Conditional Process Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Using Conditional Process Analysis to evaluate communication theories - B.A. Seminar at IKMZ, FS 2022" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Solutions | R for Conditional Process Analysis" />
  
  <meta name="twitter:description" content="Using Conditional Process Analysis to evaluate communication theories - B.A. Seminar at IKMZ, FS 2022" />
  

<meta name="author" content="Lara Kobilke, IKMZ, University of Zurich" />


<meta name="date" content="2022-04-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="exercise-6-test-your-knowledge.html"/>

<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">CPA Seminar</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>General information on the course</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-to-use-this-tutorial"><i class="fa fa-check"></i>How to use this tutorial</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-can-i-do-if-questions-arise"><i class="fa fa-check"></i>What can I do if questions arise?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-can-i-do-if-i-have-problems-with-my-r-code"><i class="fa fa-check"></i>What can I do if I have problems with my R code?</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html"><i class="fa fa-check"></i><b>1</b> Tutorial: Installing &amp; Understanding R/R Studio</a>
<ul>
<li class="chapter" data-level="1.1" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html#installing-r"><i class="fa fa-check"></i><b>1.1</b> Installing R</a></li>
<li class="chapter" data-level="1.2" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html#installing-r-studio"><i class="fa fa-check"></i><b>1.2</b> Installing R Studio</a></li>
<li class="chapter" data-level="1.3" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html#updating-r-and-r-studio"><i class="fa fa-check"></i><b>1.3</b> Updating R and R Studio</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html#on-windows"><i class="fa fa-check"></i><b>1.3.1</b> On Windows</a></li>
<li class="chapter" data-level="1.3.2" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html#on-mac"><i class="fa fa-check"></i><b>1.3.2</b> On MAC</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html#how-does-r-work"><i class="fa fa-check"></i><b>1.4</b> How does R work?</a></li>
<li class="chapter" data-level="1.5" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html#how-does-r-studio-work"><i class="fa fa-check"></i><b>1.5</b> How does R Studio work?</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html#source-writing-your-own-code"><i class="fa fa-check"></i><b>1.5.1</b> Source: Writing your own code</a></li>
<li class="chapter" data-level="1.5.2" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html#console-printing-results"><i class="fa fa-check"></i><b>1.5.2</b> Console: Printing results</a></li>
<li class="chapter" data-level="1.5.3" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html#environment-overview-of-objects"><i class="fa fa-check"></i><b>1.5.3</b> Environment: Overview of objects</a></li>
<li class="chapter" data-level="1.5.4" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html#plotshelppackages-do-everything-else"><i class="fa fa-check"></i><b>1.5.4</b> Plots/Help/Packages: Do everything else</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html#take-aways"><i class="fa fa-check"></i><b>1.6</b> Take-Aways</a></li>
<li class="chapter" data-level="1.7" data-path="tutorial-installing-understanding-rr-studio.html"><a href="tutorial-installing-understanding-rr-studio.html#more-tutorials-on-this"><i class="fa fa-check"></i><b>1.7</b> More tutorials on this</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html"><i class="fa fa-check"></i><b>2</b> Tutorial: Workflow in R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#defining-your-working-directory"><i class="fa fa-check"></i><b>2.1</b> Defining your working directory</a></li>
<li class="chapter" data-level="2.2" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#packages"><i class="fa fa-check"></i><b>2.2</b> Packages</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#installing-packages"><i class="fa fa-check"></i><b>2.2.1</b> Installing packages</a></li>
<li class="chapter" data-level="2.2.2" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#activating-packages"><i class="fa fa-check"></i><b>2.2.2</b> Activating packages</a></li>
<li class="chapter" data-level="2.2.3" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#getting-information-about-packages"><i class="fa fa-check"></i><b>2.2.3</b> Getting information about packages</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#help"><i class="fa fa-check"></i><b>2.3</b> Help?!</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#finding-information-about-packages"><i class="fa fa-check"></i><b>2.3.1</b> Finding information about packages</a></li>
<li class="chapter" data-level="2.3.2" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#finding-information-about-functions"><i class="fa fa-check"></i><b>2.3.2</b> Finding information about functions</a></li>
<li class="chapter" data-level="2.3.3" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#searching-for-help-online"><i class="fa fa-check"></i><b>2.3.3</b> Searching for help online</a></li>
<li class="chapter" data-level="2.3.4" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#interrupting-r"><i class="fa fa-check"></i><b>2.3.4</b> Interrupting R</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#saving-loading-cleaning-coderesults"><i class="fa fa-check"></i><b>2.4</b> Saving, loading &amp; cleaning code/results</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#saving-your-code"><i class="fa fa-check"></i><b>2.4.1</b> Saving your code</a></li>
<li class="chapter" data-level="2.4.2" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#saving-your-results"><i class="fa fa-check"></i><b>2.4.2</b> Saving your results</a></li>
<li class="chapter" data-level="2.4.3" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#loading-working-spaces"><i class="fa fa-check"></i><b>2.4.3</b> Loading working spaces</a></li>
<li class="chapter" data-level="2.4.4" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#clean-your-working-space"><i class="fa fa-check"></i><b>2.4.4</b> Clean your working space</a></li>
<li class="chapter" data-level="2.4.5" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#take-aways-1"><i class="fa fa-check"></i><b>2.4.5</b> Take Aways</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="tutorial-workflow-in-r.html"><a href="tutorial-workflow-in-r.html#more-tutorials-on-this-1"><i class="fa fa-check"></i><b>2.5</b> More tutorials on this</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="tutorial-using-r-as-a-calculator.html"><a href="tutorial-using-r-as-a-calculator.html"><i class="fa fa-check"></i><b>3</b> Tutorial: Using R as a calculator</a>
<ul>
<li class="chapter" data-level="3.1" data-path="tutorial-using-r-as-a-calculator.html"><a href="tutorial-using-r-as-a-calculator.html#using-variables-for-calculation"><i class="fa fa-check"></i><b>3.1</b> Using variables for calculation</a></li>
<li class="chapter" data-level="3.2" data-path="tutorial-using-r-as-a-calculator.html"><a href="tutorial-using-r-as-a-calculator.html#using-vectors-for-calculation"><i class="fa fa-check"></i><b>3.2</b> Using vectors for calculation</a></li>
<li class="chapter" data-level="3.3" data-path="tutorial-using-r-as-a-calculator.html"><a href="tutorial-using-r-as-a-calculator.html#take-aways-2"><i class="fa fa-check"></i><b>3.3</b> Take-Aways</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html"><i class="fa fa-check"></i><b>4</b> Tutorial: Objects &amp; structures in R</a>
<ul>
<li class="chapter" data-level="4.1" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#types-of-data"><i class="fa fa-check"></i><b>4.1</b> Types of data</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#accessing-variables-in-data-sets"><i class="fa fa-check"></i><b>4.1.1</b> Accessing variables in data sets</a></li>
<li class="chapter" data-level="4.1.2" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#numbers"><i class="fa fa-check"></i><b>4.1.2</b> Numbers</a></li>
<li class="chapter" data-level="4.1.3" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#text"><i class="fa fa-check"></i><b>4.1.3</b> Text</a></li>
<li class="chapter" data-level="4.1.4" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#factors"><i class="fa fa-check"></i><b>4.1.4</b> Factors</a></li>
<li class="chapter" data-level="4.1.5" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#dates"><i class="fa fa-check"></i><b>4.1.5</b> Dates</a></li>
<li class="chapter" data-level="4.1.6" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#missing-datanas"><i class="fa fa-check"></i><b>4.1.6</b> Missing data/NAs</a></li>
<li class="chapter" data-level="4.1.7" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#logicalother-operators"><i class="fa fa-check"></i><b>4.1.7</b> Logical/other operators</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#types-of-objects"><i class="fa fa-check"></i><b>4.2</b> Types of objects</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#scalars"><i class="fa fa-check"></i><b>4.2.1</b> Scalars</a></li>
<li class="chapter" data-level="4.2.2" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#vectors"><i class="fa fa-check"></i><b>4.2.2</b> Vectors</a></li>
<li class="chapter" data-level="4.2.3" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#data-frames-matrices"><i class="fa fa-check"></i><b>4.2.3</b> Data frames &amp; matrices</a></li>
<li class="chapter" data-level="4.2.4" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#lists"><i class="fa fa-check"></i><b>4.2.4</b> Lists</a></li>
<li class="chapter" data-level="4.2.5" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#other-types-of-objects"><i class="fa fa-check"></i><b>4.2.5</b> Other types of objects</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#take-aways-3"><i class="fa fa-check"></i><b>4.3</b> Take Aways</a></li>
<li class="chapter" data-level="4.4" data-path="tutorial-objects-structures-in-r.html"><a href="tutorial-objects-structures-in-r.html#more-tutorials-on-this-2"><i class="fa fa-check"></i><b>4.4</b> More tutorials on this</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tutorial-reading-data-inout.html"><a href="tutorial-reading-data-inout.html"><i class="fa fa-check"></i><b>5</b> Tutorial: Reading data in/out</a>
<ul>
<li class="chapter" data-level="5.1" data-path="tutorial-reading-data-inout.html"><a href="tutorial-reading-data-inout.html#getting-data-into-r"><i class="fa fa-check"></i><b>5.1</b> Getting data into R</a></li>
<li class="chapter" data-level="5.2" data-path="tutorial-reading-data-inout.html"><a href="tutorial-reading-data-inout.html#getting-data-out-of-r"><i class="fa fa-check"></i><b>5.2</b> Getting data out of R</a></li>
<li class="chapter" data-level="5.3" data-path="tutorial-reading-data-inout.html"><a href="tutorial-reading-data-inout.html#other-packages-for-getting-data-intoout-of-r"><i class="fa fa-check"></i><b>5.3</b> Other packages for getting data into/out of R</a></li>
<li class="chapter" data-level="5.4" data-path="tutorial-reading-data-inout.html"><a href="tutorial-reading-data-inout.html#take-aways-4"><i class="fa fa-check"></i><b>5.4</b> Take Aways</a></li>
<li class="chapter" data-level="5.5" data-path="tutorial-reading-data-inout.html"><a href="tutorial-reading-data-inout.html#more-tutorials-on-this-3"><i class="fa fa-check"></i><b>5.5</b> More tutorials on this</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="exercise-1-test-your-knowledge.html"><a href="exercise-1-test-your-knowledge.html"><i class="fa fa-check"></i><b>6</b> Exercise 1: Test your knowledge</a>
<ul>
<li class="chapter" data-level="6.1" data-path="exercise-1-test-your-knowledge.html"><a href="exercise-1-test-your-knowledge.html#task-1"><i class="fa fa-check"></i><b>6.1</b> Task 1</a></li>
<li class="chapter" data-level="6.2" data-path="exercise-1-test-your-knowledge.html"><a href="exercise-1-test-your-knowledge.html#task-2"><i class="fa fa-check"></i><b>6.2</b> Task 2</a></li>
<li class="chapter" data-level="6.3" data-path="exercise-1-test-your-knowledge.html"><a href="exercise-1-test-your-knowledge.html#task-3"><i class="fa fa-check"></i><b>6.3</b> Task 3</a></li>
<li class="chapter" data-level="6.4" data-path="exercise-1-test-your-knowledge.html"><a href="exercise-1-test-your-knowledge.html#task-4"><i class="fa fa-check"></i><b>6.4</b> Task 4</a></li>
<li class="chapter" data-level="6.5" data-path="exercise-1-test-your-knowledge.html"><a href="exercise-1-test-your-knowledge.html#task-5"><i class="fa fa-check"></i><b>6.5</b> Task 5</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html"><i class="fa fa-check"></i><b>7</b> Tutorial: Data management with tidyverse</a>
<ul>
<li class="chapter" data-level="7.1" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html#why-not-stick-with-base-r"><i class="fa fa-check"></i><b>7.1</b> Why not stick with Base R?</a></li>
<li class="chapter" data-level="7.2" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html#tidyverse-packages"><i class="fa fa-check"></i><b>7.2</b> Tidyverse packages</a></li>
<li class="chapter" data-level="7.3" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html#tidy-data"><i class="fa fa-check"></i><b>7.3</b> Tidy data</a></li>
<li class="chapter" data-level="7.4" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html#the-pipe-operator"><i class="fa fa-check"></i><b>7.4</b> The pipe operator</a></li>
<li class="chapter" data-level="7.5" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html#data-transformation-with-dplyr"><i class="fa fa-check"></i><b>7.5</b> Data transformation with dplyr</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html#select"><i class="fa fa-check"></i><b>7.5.1</b> select()</a></li>
<li class="chapter" data-level="7.5.2" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html#filter"><i class="fa fa-check"></i><b>7.5.2</b> filter()</a></li>
<li class="chapter" data-level="7.5.3" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html#arrange"><i class="fa fa-check"></i><b>7.5.3</b> arrange()</a></li>
<li class="chapter" data-level="7.5.4" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html#mutate"><i class="fa fa-check"></i><b>7.5.4</b> mutate()</a></li>
<li class="chapter" data-level="7.5.5" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html#simmarize-group_by"><i class="fa fa-check"></i><b>7.5.5</b> simmarize() [+ group_by()]</a></li>
<li class="chapter" data-level="7.5.6" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html#chaining-functions-in-a-pipe"><i class="fa fa-check"></i><b>7.5.6</b> Chaining functions in a pipe</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html#take-aways-5"><i class="fa fa-check"></i><b>7.6</b> Take-Aways</a></li>
<li class="chapter" data-level="7.7" data-path="tutorial-data-management-with-tidyverse.html"><a href="tutorial-data-management-with-tidyverse.html#more-tutorials-on-this-4"><i class="fa fa-check"></i><b>7.7</b> More tutorials on this</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="exercise-2-test-your-knowledge.html"><a href="exercise-2-test-your-knowledge.html"><i class="fa fa-check"></i><b>8</b> Exercise 2: Test your knowledge</a>
<ul>
<li class="chapter" data-level="8.1" data-path="exercise-2-test-your-knowledge.html"><a href="exercise-2-test-your-knowledge.html#task-1-1"><i class="fa fa-check"></i><b>8.1</b> Task 1</a></li>
<li class="chapter" data-level="8.2" data-path="exercise-2-test-your-knowledge.html"><a href="exercise-2-test-your-knowledge.html#task-2-1"><i class="fa fa-check"></i><b>8.2</b> Task 2</a></li>
<li class="chapter" data-level="8.3" data-path="exercise-2-test-your-knowledge.html"><a href="exercise-2-test-your-knowledge.html#task-3-1"><i class="fa fa-check"></i><b>8.3</b> Task 3</a></li>
<li class="chapter" data-level="8.4" data-path="exercise-2-test-your-knowledge.html"><a href="exercise-2-test-your-knowledge.html#task-4-1"><i class="fa fa-check"></i><b>8.4</b> Task 4</a></li>
<li class="chapter" data-level="8.5" data-path="exercise-2-test-your-knowledge.html"><a href="exercise-2-test-your-knowledge.html#task-5-1"><i class="fa fa-check"></i><b>8.5</b> Task 5</a></li>
<li class="chapter" data-level="8.6" data-path="exercise-2-test-your-knowledge.html"><a href="exercise-2-test-your-knowledge.html#task-6"><i class="fa fa-check"></i><b>8.6</b> Task 6</a></li>
<li class="chapter" data-level="8.7" data-path="exercise-2-test-your-knowledge.html"><a href="exercise-2-test-your-knowledge.html#task-7"><i class="fa fa-check"></i><b>8.7</b> Task 7</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html"><i class="fa fa-check"></i><b>9</b> Tutorial: Data visualization with ggplot</a>
<ul>
<li class="chapter" data-level="9.1" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#why-not-stick-with-base-r-1"><i class="fa fa-check"></i><b>9.1</b> Why not stick with Base R?</a></li>
<li class="chapter" data-level="9.2" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#components-of-a-ggplot-graph"><i class="fa fa-check"></i><b>9.2</b> Components of a ggplot graph</a></li>
<li class="chapter" data-level="9.3" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#installing-activating-ggplot"><i class="fa fa-check"></i><b>9.3</b> Installing &amp; activating ggplot</a></li>
<li class="chapter" data-level="9.4" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#building-your-first-plot"><i class="fa fa-check"></i><b>9.4</b> Building your first plot</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#data"><i class="fa fa-check"></i><b>9.4.1</b> Data</a></li>
<li class="chapter" data-level="9.4.2" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#aesthetics"><i class="fa fa-check"></i><b>9.4.2</b> Aesthetics</a></li>
<li class="chapter" data-level="9.4.3" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#geometrics"><i class="fa fa-check"></i><b>9.4.3</b> Geometrics</a></li>
<li class="chapter" data-level="9.4.4" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#scales"><i class="fa fa-check"></i><b>9.4.4</b> Scales</a></li>
<li class="chapter" data-level="9.4.5" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#themes"><i class="fa fa-check"></i><b>9.4.5</b> Themes</a></li>
<li class="chapter" data-level="9.4.6" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#labs"><i class="fa fa-check"></i><b>9.4.6</b> Labs</a></li>
<li class="chapter" data-level="9.4.7" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#facets"><i class="fa fa-check"></i><b>9.4.7</b> Facets</a></li>
<li class="chapter" data-level="9.4.8" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#saving-graphs"><i class="fa fa-check"></i><b>9.4.8</b> Saving graphs</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#other-common-plot-types"><i class="fa fa-check"></i><b>9.5</b> Other common plot types</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#bar-plots"><i class="fa fa-check"></i><b>9.5.1</b> bar plots</a></li>
<li class="chapter" data-level="9.5.2" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#box-plots"><i class="fa fa-check"></i><b>9.5.2</b> box plots</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#take-aways-6"><i class="fa fa-check"></i><b>9.6</b> Take Aways</a></li>
<li class="chapter" data-level="9.7" data-path="tutorial-data-visualization-with-ggplot.html"><a href="tutorial-data-visualization-with-ggplot.html#more-tutorials-on-this-5"><i class="fa fa-check"></i><b>9.7</b> More tutorials on this</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="exercise-3-test-your-knowledge.html"><a href="exercise-3-test-your-knowledge.html"><i class="fa fa-check"></i><b>10</b> Exercise 3: Test your knowledge</a>
<ul>
<li class="chapter" data-level="10.1" data-path="exercise-3-test-your-knowledge.html"><a href="exercise-3-test-your-knowledge.html#task-1-2"><i class="fa fa-check"></i><b>10.1</b> Task 1</a></li>
<li class="chapter" data-level="10.2" data-path="exercise-3-test-your-knowledge.html"><a href="exercise-3-test-your-knowledge.html#task-2-2"><i class="fa fa-check"></i><b>10.2</b> Task 2</a></li>
<li class="chapter" data-level="10.3" data-path="exercise-3-test-your-knowledge.html"><a href="exercise-3-test-your-knowledge.html#task-3-2"><i class="fa fa-check"></i><b>10.3</b> Task 3</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="tutorial-linear-regression.html"><a href="tutorial-linear-regression.html"><i class="fa fa-check"></i><b>11</b> Tutorial: Linear regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="tutorial-linear-regression.html"><a href="tutorial-linear-regression.html#knowing-your-data"><i class="fa fa-check"></i><b>11.1</b> Knowing your data</a></li>
<li class="chapter" data-level="11.2" data-path="tutorial-linear-regression.html"><a href="tutorial-linear-regression.html#visual-inspection-of-linear-trends"><i class="fa fa-check"></i><b>11.2</b> Visual inspection of linear trends</a></li>
<li class="chapter" data-level="11.3" data-path="tutorial-linear-regression.html"><a href="tutorial-linear-regression.html#pearsons-r"><i class="fa fa-check"></i><b>11.3</b> Pearson´s r</a></li>
<li class="chapter" data-level="11.4" data-path="tutorial-linear-regression.html"><a href="tutorial-linear-regression.html#ols-regression"><i class="fa fa-check"></i><b>11.4</b> OLS regression</a></li>
<li class="chapter" data-level="11.5" data-path="tutorial-linear-regression.html"><a href="tutorial-linear-regression.html#standardizing-coefficients"><i class="fa fa-check"></i><b>11.5</b> Standardizing coefficients</a></li>
<li class="chapter" data-level="11.6" data-path="tutorial-linear-regression.html"><a href="tutorial-linear-regression.html#multiple-regression"><i class="fa fa-check"></i><b>11.6</b> Multiple regression</a></li>
<li class="chapter" data-level="11.7" data-path="tutorial-linear-regression.html"><a href="tutorial-linear-regression.html#standardized-multiple-regression"><i class="fa fa-check"></i><b>11.7</b> Standardized multiple regression</a></li>
<li class="chapter" data-level="11.8" data-path="tutorial-linear-regression.html"><a href="tutorial-linear-regression.html#take-aways-7"><i class="fa fa-check"></i><b>11.8</b> Take Aways</a></li>
<li class="chapter" data-level="11.9" data-path="tutorial-linear-regression.html"><a href="tutorial-linear-regression.html#more-tutorials-on-this-6"><i class="fa fa-check"></i><b>11.9</b> More tutorials on this</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="exercise-4-test-your-knowledge.html"><a href="exercise-4-test-your-knowledge.html"><i class="fa fa-check"></i><b>12</b> Exercise 4: Test your knowledge</a>
<ul>
<li class="chapter" data-level="12.1" data-path="exercise-4-test-your-knowledge.html"><a href="exercise-4-test-your-knowledge.html#task-1-3"><i class="fa fa-check"></i><b>12.1</b> Task 1</a></li>
<li class="chapter" data-level="12.2" data-path="exercise-4-test-your-knowledge.html"><a href="exercise-4-test-your-knowledge.html#task-2-3"><i class="fa fa-check"></i><b>12.2</b> Task 2</a></li>
<li class="chapter" data-level="12.3" data-path="exercise-4-test-your-knowledge.html"><a href="exercise-4-test-your-knowledge.html#task-3-3"><i class="fa fa-check"></i><b>12.3</b> Task 3</a></li>
<li class="chapter" data-level="12.4" data-path="exercise-4-test-your-knowledge.html"><a href="exercise-4-test-your-knowledge.html#task-4-2"><i class="fa fa-check"></i><b>12.4</b> Task 4</a></li>
<li class="chapter" data-level="12.5" data-path="exercise-4-test-your-knowledge.html"><a href="exercise-4-test-your-knowledge.html#task-5-2"><i class="fa fa-check"></i><b>12.5</b> Task 5</a></li>
<li class="chapter" data-level="12.6" data-path="exercise-4-test-your-knowledge.html"><a href="exercise-4-test-your-knowledge.html#task-6-1"><i class="fa fa-check"></i><b>12.6</b> Task 6</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html"><i class="fa fa-check"></i><b>13</b> Tutorial: Mediation analysis</a>
<ul>
<li class="chapter" data-level="13.1" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#introduction-to-mediation"><i class="fa fa-check"></i><b>13.1</b> Introduction to mediation</a></li>
<li class="chapter" data-level="13.2" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#difference-between-mediation-and-moderation"><i class="fa fa-check"></i><b>13.2</b> Difference between mediation and moderation</a></li>
<li class="chapter" data-level="13.3" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#two-step-process-of-mediation"><i class="fa fa-check"></i><b>13.3</b> Two-step process of mediation</a></li>
<li class="chapter" data-level="13.4" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#statistical-representation-and-equations"><i class="fa fa-check"></i><b>13.4</b> Statistical representation and equations</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#direct-effect-c"><i class="fa fa-check"></i><b>13.4.1</b> Direct effect <em>c′</em></a></li>
<li class="chapter" data-level="13.4.2" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#indirect-effect-ab"><i class="fa fa-check"></i><b>13.4.2</b> Indirect effect <em>ab</em></a></li>
<li class="chapter" data-level="13.4.3" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#total-effect"><i class="fa fa-check"></i><b>13.4.3</b> Total effect</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#example"><i class="fa fa-check"></i><b>13.5</b> Example</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#knowing-your-data-1"><i class="fa fa-check"></i><b>13.5.1</b> Knowing your data</a></li>
<li class="chapter" data-level="13.5.2" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#visual-inspection-of-linear-trends-1"><i class="fa fa-check"></i><b>13.5.2</b> Visual inspection of linear trends</a></li>
<li class="chapter" data-level="13.5.3" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#pearsons-r-1"><i class="fa fa-check"></i><b>13.5.3</b> Pearson’s r</a></li>
<li class="chapter" data-level="13.5.4" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#fit-models"><i class="fa fa-check"></i><b>13.5.4</b> Fit models</a></li>
<li class="chapter" data-level="13.5.5" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#using-processr"><i class="fa fa-check"></i><b>13.5.5</b> Using processR</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#take-aways-8"><i class="fa fa-check"></i><b>13.6</b> Take Aways</a></li>
<li class="chapter" data-level="13.7" data-path="tutorial-mediation-analysis.html"><a href="tutorial-mediation-analysis.html#more-tutorials-on-this-7"><i class="fa fa-check"></i><b>13.7</b> More tutorials on this</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="exercise-5-test-your-knowledge.html"><a href="exercise-5-test-your-knowledge.html"><i class="fa fa-check"></i><b>14</b> Exercise 5: Test your knowledge</a>
<ul>
<li class="chapter" data-level="14.1" data-path="exercise-5-test-your-knowledge.html"><a href="exercise-5-test-your-knowledge.html#task-1-4"><i class="fa fa-check"></i><b>14.1</b> Task 1</a></li>
<li class="chapter" data-level="14.2" data-path="exercise-5-test-your-knowledge.html"><a href="exercise-5-test-your-knowledge.html#task-2-4"><i class="fa fa-check"></i><b>14.2</b> Task 2</a></li>
<li class="chapter" data-level="14.3" data-path="exercise-5-test-your-knowledge.html"><a href="exercise-5-test-your-knowledge.html#task-3-4"><i class="fa fa-check"></i><b>14.3</b> Task 3</a></li>
<li class="chapter" data-level="14.4" data-path="exercise-5-test-your-knowledge.html"><a href="exercise-5-test-your-knowledge.html#task-4-3"><i class="fa fa-check"></i><b>14.4</b> Task 4</a></li>
<li class="chapter" data-level="14.5" data-path="exercise-5-test-your-knowledge.html"><a href="exercise-5-test-your-knowledge.html#task-5-3"><i class="fa fa-check"></i><b>14.5</b> Task 5</a></li>
<li class="chapter" data-level="14.6" data-path="exercise-5-test-your-knowledge.html"><a href="exercise-5-test-your-knowledge.html#task-6-2"><i class="fa fa-check"></i><b>14.6</b> Task 6</a></li>
<li class="chapter" data-level="14.7" data-path="exercise-5-test-your-knowledge.html"><a href="exercise-5-test-your-knowledge.html#task-7-1"><i class="fa fa-check"></i><b>14.7</b> Task 7</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="tutorial-moderation-analysis.html"><a href="tutorial-moderation-analysis.html"><i class="fa fa-check"></i><b>15</b> Tutorial: Moderation analysis</a>
<ul>
<li class="chapter" data-level="15.1" data-path="tutorial-moderation-analysis.html"><a href="tutorial-moderation-analysis.html#introduction-to-moderation"><i class="fa fa-check"></i><b>15.1</b> Introduction to moderation</a></li>
<li class="chapter" data-level="15.2" data-path="tutorial-moderation-analysis.html"><a href="tutorial-moderation-analysis.html#one-step-process-of-moderation"><i class="fa fa-check"></i><b>15.2</b> One-step process of moderation</a></li>
<li class="chapter" data-level="15.3" data-path="tutorial-moderation-analysis.html"><a href="tutorial-moderation-analysis.html#statistical-representation-and-equations-1"><i class="fa fa-check"></i><b>15.3</b> Statistical representation and equations</a></li>
<li class="chapter" data-level="15.4" data-path="tutorial-moderation-analysis.html"><a href="tutorial-moderation-analysis.html#example-1"><i class="fa fa-check"></i><b>15.4</b> Example</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="tutorial-moderation-analysis.html"><a href="tutorial-moderation-analysis.html#knowing-your-data-2"><i class="fa fa-check"></i><b>15.4.1</b> Knowing your data</a></li>
<li class="chapter" data-level="15.4.2" data-path="tutorial-moderation-analysis.html"><a href="tutorial-moderation-analysis.html#visual-inspection-of-linear-trends-2"><i class="fa fa-check"></i><b>15.4.2</b> Visual inspection of linear trends</a></li>
<li class="chapter" data-level="15.4.3" data-path="tutorial-moderation-analysis.html"><a href="tutorial-moderation-analysis.html#fit-models-1"><i class="fa fa-check"></i><b>15.4.3</b> Fit models</a></li>
<li class="chapter" data-level="15.4.4" data-path="tutorial-moderation-analysis.html"><a href="tutorial-moderation-analysis.html#standardization-and-mean-centering"><i class="fa fa-check"></i><b>15.4.4</b> Standardization and mean-centering</a></li>
<li class="chapter" data-level="15.4.5" data-path="tutorial-moderation-analysis.html"><a href="tutorial-moderation-analysis.html#follow-up-analysis-pobing-the-interaction"><i class="fa fa-check"></i><b>15.4.5</b> Follow-up analysis: Pobing the interaction</a></li>
<li class="chapter" data-level="15.4.6" data-path="tutorial-moderation-analysis.html"><a href="tutorial-moderation-analysis.html#using-processr-1"><i class="fa fa-check"></i><b>15.4.6</b> Using processR</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="tutorial-moderation-analysis.html"><a href="tutorial-moderation-analysis.html#take-aways-9"><i class="fa fa-check"></i><b>15.5</b> Take Aways</a></li>
<li class="chapter" data-level="15.6" data-path="tutorial-moderation-analysis.html"><a href="tutorial-moderation-analysis.html#more-tutorials-on-this-8"><i class="fa fa-check"></i><b>15.6</b> More tutorials on this</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="exercise-6-test-your-knowledge.html"><a href="exercise-6-test-your-knowledge.html"><i class="fa fa-check"></i><b>16</b> Exercise 6: Test your knowledge</a>
<ul>
<li class="chapter" data-level="16.1" data-path="exercise-6-test-your-knowledge.html"><a href="exercise-6-test-your-knowledge.html#task-1-5"><i class="fa fa-check"></i><b>16.1</b> Task 1</a></li>
<li class="chapter" data-level="16.2" data-path="exercise-6-test-your-knowledge.html"><a href="exercise-6-test-your-knowledge.html#task-2-5"><i class="fa fa-check"></i><b>16.2</b> Task 2</a></li>
<li class="chapter" data-level="16.3" data-path="exercise-6-test-your-knowledge.html"><a href="exercise-6-test-your-knowledge.html#task-3-5"><i class="fa fa-check"></i><b>16.3</b> Task 3</a></li>
<li class="chapter" data-level="16.4" data-path="exercise-6-test-your-knowledge.html"><a href="exercise-6-test-your-knowledge.html#task-4-4"><i class="fa fa-check"></i><b>16.4</b> Task 4</a></li>
<li class="chapter" data-level="16.5" data-path="exercise-6-test-your-knowledge.html"><a href="exercise-6-test-your-knowledge.html#task-5-4"><i class="fa fa-check"></i><b>16.5</b> Task 5</a></li>
<li class="chapter" data-level="16.6" data-path="exercise-6-test-your-knowledge.html"><a href="exercise-6-test-your-knowledge.html#task-6-3"><i class="fa fa-check"></i><b>16.6</b> Task 6</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html"><i class="fa fa-check"></i>Solutions</a>
<ul>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#solutions-for-exercise-1"><i class="fa fa-check"></i>Solutions for Exercise 1</a>
<ul>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-1-6"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-2-6"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-3-6"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-4-5"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-5-5"><i class="fa fa-check"></i>Task 5</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#solutions-for-exercise-2"><i class="fa fa-check"></i>Solutions for Exercise 2</a>
<ul>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-1-7"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-2-7"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-3-7"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-4-6"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-5-6"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-6-4"><i class="fa fa-check"></i>Task 6</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-7-2"><i class="fa fa-check"></i>Task 7</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#solutions-for-exercise-3"><i class="fa fa-check"></i>Solutions for Exercise 3</a>
<ul>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-1-8"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-2-8"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-3-8"><i class="fa fa-check"></i>Task 3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#solutions-for-exercise-4"><i class="fa fa-check"></i>Solutions for Exercise 4</a>
<ul>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-1-9"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-2-9"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-3-9"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-4-7"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-5-7"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-6-5"><i class="fa fa-check"></i>Task 6</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#solutions-for-exercise-5"><i class="fa fa-check"></i>Solutions for Exercise 5</a>
<ul>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-1-10"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-2-10"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-3-10"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-4-8"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-5-8"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-6-6"><i class="fa fa-check"></i>Task 6</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-7-3"><i class="fa fa-check"></i>Task 7</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#solutions-for-exercise-6"><i class="fa fa-check"></i>Solutions for Exercise 6</a>
<ul>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-1-11"><i class="fa fa-check"></i>Task 1</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-2-11"><i class="fa fa-check"></i>Task 2</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-3-11"><i class="fa fa-check"></i>Task 3</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-4-9"><i class="fa fa-check"></i>Task 4</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-5-9"><i class="fa fa-check"></i>Task 5</a></li>
<li class="chapter" data-level="" data-path="solutions.html"><a href="solutions.html#task-6-7"><i class="fa fa-check"></i>Task 6</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/LKobilke/CPA-Seminar" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for Conditional Process Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="solutions" class="section level1 unnumbered">
<h1>Solutions</h1>
<p>This is where you’ll find solutions for all of the tutorials.</p>
<div id="solutions-for-exercise-1" class="section level2 unnumbered">
<h2>Solutions for Exercise 1</h2>
<div id="task-1-6" class="section level3 unnumbered">
<h3>Task 1</h3>
<p>Below you will see multiple choice questions. Please try to identify the correct answers. 1, 2, 3 and 4 correct answers are possible for each question.</p>
<p><strong>1. What panels are part of RStudio?</strong></p>
<p><em>Solution:</em></p>
<ul>
<li>source (x)</li>
<li>console (x)</li>
<li>packages, files &amp; plots (x)</li>
</ul>
<p><strong>2. How do you activate R packages after you have installed them?</strong></p>
<p><em>Solution:</em></p>
<ul>
<li>library() (x)</li>
</ul>
<p><strong>3. How do you create a vector in R with elements 1, 2, 3?</strong></p>
<p><em>Solution:</em></p>
<ul>
<li>c(1,2,3) (x)</li>
</ul>
<p><strong>4. Imagine you have a vector called ‘vector’ with 10 numeric elements. How do you retrieve the 8th element?</strong></p>
<p><em>Solution:</em></p>
<ul>
<li>vector[8] (x)</li>
</ul>
<p><strong>5. Imagine you have a vector called ‘hair’ with 5 elements: brown, black, red, blond, other. How do you retrieve the color ‘blond’?</strong></p>
<p><em>Solution:</em></p>
<ul>
<li>hair[4] (x)</li>
</ul>
</div>
<div id="task-2-6" class="section level3 unnumbered">
<h3>Task 2</h3>
<p>Create a numeric vector with 8 values and assign the name <em>age</em> to the vector. First, display all elements of the vector. Then print only the 5th element. After that, display all elements except the 5th. Finally, display the elements at the positions 6 to 8.</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="solutions.html#cb305-1" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">65</span>,<span class="dv">52</span>,<span class="dv">73</span>,<span class="dv">71</span>,<span class="dv">80</span>,<span class="dv">62</span>,<span class="dv">68</span>,<span class="dv">87</span>)</span>
<span id="cb305-2"><a href="solutions.html#cb305-2" aria-hidden="true" tabindex="-1"></a>age</span></code></pre></div>
<pre><code>## [1] 65 52 73 71 80 62 68 87</code></pre>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="solutions.html#cb307-1" aria-hidden="true" tabindex="-1"></a>age[<span class="dv">5</span>]</span></code></pre></div>
<pre><code>## [1] 80</code></pre>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="solutions.html#cb309-1" aria-hidden="true" tabindex="-1"></a>age[<span class="sc">-</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>## [1] 65 52 73 71 62 68 87</code></pre>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="solutions.html#cb311-1" aria-hidden="true" tabindex="-1"></a>age[<span class="dv">6</span><span class="sc">:</span><span class="dv">8</span>]</span></code></pre></div>
<pre><code>## [1] 62 68 87</code></pre>
</div>
<div id="task-3-6" class="section level3 unnumbered">
<h3>Task 3</h3>
<p>Create a non-numeric, i.e. character, vector with 4 elements and assign the name <em>eye_color</em> to the vector. First, print all elements of this vector to the console. Then have only the value in the 2nd element displayed, then all values except the 2nd element. At the end, display the elements at the positions 2 to 4.</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="solutions.html#cb313-1" aria-hidden="true" tabindex="-1"></a>eye_color <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;green&quot;</span>, <span class="st">&quot;brown&quot;</span>, <span class="st">&quot;other&quot;</span>)</span>
<span id="cb313-2"><a href="solutions.html#cb313-2" aria-hidden="true" tabindex="-1"></a>eye_color</span></code></pre></div>
<pre><code>## [1] &quot;blue&quot;  &quot;green&quot; &quot;brown&quot; &quot;other&quot;</code></pre>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="solutions.html#cb315-1" aria-hidden="true" tabindex="-1"></a>eye_color[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] &quot;green&quot;</code></pre>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="solutions.html#cb317-1" aria-hidden="true" tabindex="-1"></a>eye_color[<span class="sc">-</span><span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] &quot;blue&quot;  &quot;brown&quot; &quot;other&quot;</code></pre>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="solutions.html#cb319-1" aria-hidden="true" tabindex="-1"></a>eye_color[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]</span></code></pre></div>
<pre><code>## [1] &quot;green&quot; &quot;brown&quot; &quot;other&quot;</code></pre>
</div>
<div id="task-4-5" class="section level3 unnumbered">
<h3>Task 4</h3>
<p>Create a data frame called <em>data</em>. The data frame should contain the following variables (in this order):</p>
<ul>
<li>a vector called <em>food</em>. It should contain 5 elements, namely the names of your five favorite dishes.</li>
<li>a vector called <em>description</em>. For every dish mentioned in <em>food</em>, please describe the dish in a single sentence (for instance, if the first food you describe is “pizza”, you could write: “This is an Italian dish, which I prefer with a lot of cheese.”)</li>
<li>a vector called <em>rating</em>. Rate every dish mentioned in <em>food</em> with 1-5 (using every number only once), i.e., by rating your absolute favorite dish out of all five with a 1 and your least favorite dish out of all five with a 5.</li>
</ul>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="solutions.html#cb321-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">&quot;food&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;pizza&quot;</span>, <span class="st">&quot;pasta&quot;</span>, <span class="st">&quot;ice cream&quot;</span>, <span class="st">&quot;crisps&quot;</span>, <span class="st">&quot;passion fruit&quot;</span>),</span>
<span id="cb321-2"><a href="solutions.html#cb321-2" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;description&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Italian dish, I actually prefer mine with little cheese&quot;</span>,</span>
<span id="cb321-3"><a href="solutions.html#cb321-3" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">&quot;Another Italian dish&quot;</span>,</span>
<span id="cb321-4"><a href="solutions.html#cb321-4" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">&quot;The perfect snack in summer&quot;</span>,</span>
<span id="cb321-5"><a href="solutions.html#cb321-5" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">&quot;Potatoes and oil - a luxurious combination&quot;</span>,</span>
<span id="cb321-6"><a href="solutions.html#cb321-6" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">&quot;A fruit that makes me think about  vacation&quot;</span>),</span>
<span id="cb321-7"><a href="solutions.html#cb321-7" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;Rating&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>))</span>
<span id="cb321-8"><a href="solutions.html#cb321-8" aria-hidden="true" tabindex="-1"></a>data</span></code></pre></div>
<pre><code>##            food                                             description Rating
## 1         pizza Italian dish, I actually prefer mine with little cheese      3
## 2         pasta                                    Another Italian dish      1
## 3     ice cream                             The perfect snack in summer      2
## 4        crisps              Potatoes and oil - a luxurious combination      4
## 5 passion fruit             A fruit that makes me think about  vacation      5</code></pre>
</div>
<div id="task-5-5" class="section level3 unnumbered">
<h3>Task 5</h3>
<p>Can you sort the data in your data set by rating - with your favorite dish (i.e., the one rated “1”) on top of the list and your least favorite dish (i.e., the one rated “5”) on the bottom?</p>
<p><strong>Important</strong>: You do <em>not</em> yet know this command - you’ll have to google for the right solution. Please do and note down the exact search terms you used for googling.</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="solutions.html#cb323-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;dplyr&quot;</span>)</span>
<span id="cb323-2"><a href="solutions.html#cb323-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(Rating)</span>
<span id="cb323-3"><a href="solutions.html#cb323-3" aria-hidden="true" tabindex="-1"></a>data</span></code></pre></div>
<pre><code>##            food                                             description Rating
## 1         pasta                                    Another Italian dish      1
## 2     ice cream                             The perfect snack in summer      2
## 3         pizza Italian dish, I actually prefer mine with little cheese      3
## 4        crisps              Potatoes and oil - a luxurious combination      4
## 5 passion fruit             A fruit that makes me think about  vacation      5</code></pre>
</div>
</div>
<div id="solutions-for-exercise-2" class="section level2 unnumbered">
<h2>Solutions for Exercise 2</h2>
<div id="task-1-7" class="section level3 unnumbered">
<h3>Task 1</h3>
<p>Below you will see multiple choice questions. Please try to identify the correct answers. 1, 2, 3 and 4 correct answers are possible for each question.</p>
<p><strong>1. What are the main characteristics of tidy data?</strong></p>
<p><em>Solution:</em></p>
<ul>
<li>Every observation is a row. (x)</li>
</ul>
<p><strong>2. What are <code>dplyr</code> functions?</strong></p>
<p><em>Solution:</em></p>
<ul>
<li><code>mutate()</code> (x)</li>
</ul>
<p><strong>3. How can you sort the eye_color of Star Wars characters from Z to A?</strong></p>
<p><em>Solution:</em></p>
<ul>
<li><code>starwars_data %&gt;% arrange(desc(eye_color))</code> (x)</li>
<li><code>starwars_data %&gt;% select(eye_color) %&gt;% arrange(desc(eye_color))</code> (x)</li>
</ul>
<p><strong>4. Imagine you want to recode the height of the these characters. You want to have three categories from small and medium to tall. What is a valid approach?</strong></p>
<p><em>Solution:</em></p>
<ul>
<li><code>starwars_data %&gt;% mutate(height = case_when(height&lt;=150~"small",height&lt;=190~"medium",height&gt;190~"tall"))</code> (x)</li>
</ul>
<p><strong>5. Imagine you want to provide a systematic overview over all hair colors and what species wear these hair colors frequently (not accounting for the skewed sampling of species)? What is a valid approach?</strong></p>
<p><em>Solution:</em></p>
<ul>
<li><code>starwars_data %&gt;% group_by(hair_color, species) %&gt;% summarize(count = n()) %&gt;% arrange(hair_color)</code> (x)</li>
</ul>
</div>
<div id="task-2-7" class="section level3 unnumbered">
<h3>Task 2</h3>
<p>Now it’s you turn. Load the starwars data like this:</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="solutions.html#cb325-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)              <span class="co"># to activate the dplyr package</span></span>
<span id="cb325-2"><a href="solutions.html#cb325-2" aria-hidden="true" tabindex="-1"></a>starwars_data <span class="ot">&lt;-</span> starwars   <span class="co"># to assign the pre-installed starwars data set (dplyr) into a source object in our environment</span></span></code></pre></div>
<p>How many humans are contained in the starwars data overall? (Hint: use <code>summarize(count = n())</code> or <code>count()</code>)?</p>
<p><em>Solution:</em></p>
<p>You can use <code>summarize(count = n())</code>:</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="solutions.html#cb326-1" aria-hidden="true" tabindex="-1"></a>starwars_data <span class="sc">%&gt;%</span></span>
<span id="cb326-2"><a href="solutions.html#cb326-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(species <span class="sc">==</span> <span class="st">&quot;Human&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb326-3"><a href="solutions.html#cb326-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   count
##   &lt;int&gt;
## 1    35</code></pre>
<p>Alternatively, you can use the <code>count()</code> function:</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="solutions.html#cb328-1" aria-hidden="true" tabindex="-1"></a>starwars_data <span class="sc">%&gt;%</span></span>
<span id="cb328-2"><a href="solutions.html#cb328-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(species <span class="sc">==</span> <span class="st">&quot;Human&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb328-3"><a href="solutions.html#cb328-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(species)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   species     n
##   &lt;chr&gt;   &lt;int&gt;
## 1 Human      35</code></pre>
</div>
<div id="task-3-7" class="section level3 unnumbered">
<h3>Task 3</h3>
<p>How many humans are contained in starwars by gender?</p>
<p><em>Solution:</em></p>
<p>You can use <code>summarize(count = n())</code>:</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="solutions.html#cb330-1" aria-hidden="true" tabindex="-1"></a>starwars_data <span class="sc">%&gt;%</span></span>
<span id="cb330-2"><a href="solutions.html#cb330-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(species <span class="sc">==</span> <span class="st">&quot;Human&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb330-3"><a href="solutions.html#cb330-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(species, gender) <span class="sc">%&gt;%</span> </span>
<span id="cb330-4"><a href="solutions.html#cb330-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 x 3
## # Groups:   species [1]
##   species gender    count
##   &lt;chr&gt;   &lt;chr&gt;     &lt;int&gt;
## 1 Human   feminine      9
## 2 Human   masculine    26</code></pre>
<p>Alternatively, you can use the <code>count()</code> function:</p>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="solutions.html#cb332-1" aria-hidden="true" tabindex="-1"></a>starwars_data <span class="sc">%&gt;%</span></span>
<span id="cb332-2"><a href="solutions.html#cb332-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(species <span class="sc">==</span> <span class="st">&quot;Human&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb332-3"><a href="solutions.html#cb332-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(species, gender)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   species gender        n
##   &lt;chr&gt;   &lt;chr&gt;     &lt;int&gt;
## 1 Human   feminine      9
## 2 Human   masculine    26</code></pre>
</div>
<div id="task-4-6" class="section level3 unnumbered">
<h3>Task 4</h3>
<p>What is the most common eye_color among Star Wars characters? (Hint: use <code>arrange()</code>)__</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="solutions.html#cb334-1" aria-hidden="true" tabindex="-1"></a>starwars_data <span class="sc">%&gt;%</span></span>
<span id="cb334-2"><a href="solutions.html#cb334-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(eye_color) <span class="sc">%&gt;%</span> </span>
<span id="cb334-3"><a href="solutions.html#cb334-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb334-4"><a href="solutions.html#cb334-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(count))</span></code></pre></div>
<pre><code>## # A tibble: 15 x 2
##    eye_color     count
##    &lt;chr&gt;         &lt;int&gt;
##  1 brown            21
##  2 blue             19
##  3 yellow           11
##  4 black            10
##  5 orange            8
##  6 red               5
##  7 hazel             3
##  8 unknown           3
##  9 blue-gray         1
## 10 dark              1
## 11 gold              1
## 12 green, yellow     1
## 13 pink              1
## 14 red, blue         1
## 15 white             1</code></pre>
</div>
<div id="task-5-6" class="section level3 unnumbered">
<h3>Task 5</h3>
<p>What is the average mass of Star Wars characters that are not human and have yellow eyes? (Hint: remove all <code>NAs</code>)__</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="solutions.html#cb336-1" aria-hidden="true" tabindex="-1"></a>starwars_data <span class="sc">%&gt;%</span></span>
<span id="cb336-2"><a href="solutions.html#cb336-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(species <span class="sc">!=</span> <span class="st">&quot;Human&quot;</span> <span class="sc">&amp;</span> eye_color<span class="sc">==</span><span class="st">&quot;yellow&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb336-3"><a href="solutions.html#cb336-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_mass =</span> <span class="fu">mean</span>(mass, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   mean_mass
##       &lt;dbl&gt;
## 1      74.1</code></pre>
</div>
<div id="task-6-4" class="section level3 unnumbered">
<h3>Task 6</h3>
<p>Compare the mean, median, and standard deviation of mass for all humans and droids. (Hint: remove all <code>NAs</code>)__</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="solutions.html#cb338-1" aria-hidden="true" tabindex="-1"></a>starwars_data <span class="sc">%&gt;%</span></span>
<span id="cb338-2"><a href="solutions.html#cb338-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(species<span class="sc">==</span><span class="st">&quot;Human&quot;</span> <span class="sc">|</span> species<span class="sc">==</span><span class="st">&quot;Droid&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb338-3"><a href="solutions.html#cb338-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(species) <span class="sc">%&gt;%</span>                                </span>
<span id="cb338-4"><a href="solutions.html#cb338-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">M =</span> <span class="fu">mean</span>(mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb338-5"><a href="solutions.html#cb338-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">Med =</span> <span class="fu">median</span>(mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb338-6"><a href="solutions.html#cb338-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">SD =</span> <span class="fu">sd</span>(mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb338-7"><a href="solutions.html#cb338-7" aria-hidden="true" tabindex="-1"></a>            )</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   species     M   Med    SD
##   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Droid    69.8  53.5  51.0
## 2 Human    82.8  79    19.4</code></pre>
</div>
<div id="task-7-2" class="section level3 unnumbered">
<h3>Task 7</h3>
<p>Create a new variable in which you store the mass in gram. Add it to the data frame.</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="solutions.html#cb340-1" aria-hidden="true" tabindex="-1"></a>starwars_data <span class="ot">&lt;-</span> starwars_data <span class="sc">%&gt;%</span></span>
<span id="cb340-2"><a href="solutions.html#cb340-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gr_mass =</span> mass<span class="sc">*</span><span class="dv">1000</span>)</span>
<span id="cb340-3"><a href="solutions.html#cb340-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb340-4"><a href="solutions.html#cb340-4" aria-hidden="true" tabindex="-1"></a>starwars_data <span class="sc">%&gt;%</span> </span>
<span id="cb340-5"><a href="solutions.html#cb340-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, species, mass, gr_mass)</span></code></pre></div>
<pre><code>## # A tibble: 87 x 4
##    name               species  mass gr_mass
##    &lt;chr&gt;              &lt;chr&gt;   &lt;dbl&gt;   &lt;dbl&gt;
##  1 Luke Skywalker     Human      77   77000
##  2 C-3PO              Droid      75   75000
##  3 R2-D2              Droid      32   32000
##  4 Darth Vader        Human     136  136000
##  5 Leia Organa        Human      49   49000
##  6 Owen Lars          Human     120  120000
##  7 Beru Whitesun lars Human      75   75000
##  8 R5-D4              Droid      32   32000
##  9 Biggs Darklighter  Human      84   84000
## 10 Obi-Wan Kenobi     Human      77   77000
## # ... with 77 more rows</code></pre>
</div>
</div>
<div id="solutions-for-exercise-3" class="section level2 unnumbered">
<h2>Solutions for Exercise 3</h2>
<div id="task-1-8" class="section level3 unnumbered">
<h3>Task 1</h3>
<p>Try to reproduce this plot with <code>dplyr</code> and <code>ggplot2</code>. (<strong>Hint:</strong> You can hide the legend by adding <code>theme(legend.position = "none")</code> to your plot.)</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="solutions.html#cb342-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb342-2"><a href="solutions.html#cb342-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">case_when</span>(</span>
<span id="cb342-3"><a href="solutions.html#cb342-3" aria-hidden="true" tabindex="-1"></a>    sex <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">&quot;Female&quot;</span>,</span>
<span id="cb342-4"><a href="solutions.html#cb342-4" aria-hidden="true" tabindex="-1"></a>    sex <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">&quot;Male&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb342-5"><a href="solutions.html#cb342-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Party =</span> <span class="fu">case_when</span>(</span>
<span id="cb342-6"><a href="solutions.html#cb342-6" aria-hidden="true" tabindex="-1"></a>    partyid <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">&quot;Democrat&quot;</span>,</span>
<span id="cb342-7"><a href="solutions.html#cb342-7" aria-hidden="true" tabindex="-1"></a>    partyid <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">&quot;Independent&quot;</span>,</span>
<span id="cb342-8"><a href="solutions.html#cb342-8" aria-hidden="true" tabindex="-1"></a>    partyid <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">&quot;Republican&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb342-9"><a href="solutions.html#cb342-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Party,<span class="at">y=</span>negemot, <span class="at">fill=</span>Party)) <span class="sc">+</span></span>
<span id="cb342-10"><a href="solutions.html#cb342-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">&quot;bar&quot;</span>, <span class="at">fun =</span> <span class="st">&quot;mean&quot;</span>) <span class="sc">+</span></span>
<span id="cb342-11"><a href="solutions.html#cb342-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb342-12"><a href="solutions.html#cb342-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb342-13"><a href="solutions.html#cb342-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Climate change attitudes of U.S. partisans by gender&quot;</span>,</span>
<span id="cb342-14"><a href="solutions.html#cb342-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Negative emotions about climate change&quot;</span>) <span class="sc">+</span></span>
<span id="cb342-15"><a href="solutions.html#cb342-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>sex, <span class="at">nrow=</span><span class="dv">2</span>)</span></code></pre></div>
</div>
<div id="task-2-8" class="section level3 unnumbered">
<h3>Task 2</h3>
<p>Now, try to reproduce this graph. (<strong>Hint:</strong> You will need to recode the <em>ideology</em> variable in a way that higher values represent stronger attitudes, <em>independent of partisanship</em>.)</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="solutions.html#cb343-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb343-2"><a href="solutions.html#cb343-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ideology_ext =</span> <span class="fu">case_when</span>(</span>
<span id="cb343-3"><a href="solutions.html#cb343-3" aria-hidden="true" tabindex="-1"></a>    ideology <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">4</span>,</span>
<span id="cb343-4"><a href="solutions.html#cb343-4" aria-hidden="true" tabindex="-1"></a>    ideology <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb343-5"><a href="solutions.html#cb343-5" aria-hidden="true" tabindex="-1"></a>    ideology <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb343-6"><a href="solutions.html#cb343-6" aria-hidden="true" tabindex="-1"></a>    ideology <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb343-7"><a href="solutions.html#cb343-7" aria-hidden="true" tabindex="-1"></a>    ideology <span class="sc">==</span> <span class="dv">5</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb343-8"><a href="solutions.html#cb343-8" aria-hidden="true" tabindex="-1"></a>    ideology <span class="sc">==</span> <span class="dv">6</span> <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb343-9"><a href="solutions.html#cb343-9" aria-hidden="true" tabindex="-1"></a>    ideology <span class="sc">==</span> <span class="dv">7</span> <span class="sc">~</span> <span class="dv">4</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb343-10"><a href="solutions.html#cb343-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">case_when</span>(</span>
<span id="cb343-11"><a href="solutions.html#cb343-11" aria-hidden="true" tabindex="-1"></a>    sex <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">&quot;Female&quot;</span>,</span>
<span id="cb343-12"><a href="solutions.html#cb343-12" aria-hidden="true" tabindex="-1"></a>    sex <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">&quot;Male&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb343-13"><a href="solutions.html#cb343-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Party =</span> <span class="fu">case_when</span>(</span>
<span id="cb343-14"><a href="solutions.html#cb343-14" aria-hidden="true" tabindex="-1"></a>    partyid <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">&quot;Democrat&quot;</span>,</span>
<span id="cb343-15"><a href="solutions.html#cb343-15" aria-hidden="true" tabindex="-1"></a>    partyid <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">&quot;Independent&quot;</span>,</span>
<span id="cb343-16"><a href="solutions.html#cb343-16" aria-hidden="true" tabindex="-1"></a>    partyid <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">&quot;Republican&quot;</span>))</span></code></pre></div>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="solutions.html#cb344-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb344-2"><a href="solutions.html#cb344-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Party,<span class="at">y=</span>ideology_ext, <span class="at">fill=</span>Party)) <span class="sc">+</span></span>
<span id="cb344-3"><a href="solutions.html#cb344-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb344-4"><a href="solutions.html#cb344-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb344-5"><a href="solutions.html#cb344-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb344-6"><a href="solutions.html#cb344-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Ideological extremity of U.S. partisans by gender&quot;</span>,</span>
<span id="cb344-7"><a href="solutions.html#cb344-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Ideological extremity&quot;</span>) <span class="sc">+</span></span>
<span id="cb344-8"><a href="solutions.html#cb344-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>sex)</span></code></pre></div>
</div>
<div id="task-3-8" class="section level3 unnumbered">
<h3>Task 3</h3>
<p>Can you make a chart that breaks down the relationship between <em>age</em>, <em>negative emotions about climate change</em>, and <em>ideological extremity</em> for the different <em>sexes</em> AND <em>parties</em>?</p>
<p><em>Solution 1:</em></p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="solutions.html#cb345-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb345-2"><a href="solutions.html#cb345-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>age,<span class="at">y=</span>negemot, <span class="at">size=</span>ideology_ext, <span class="at">color =</span> Party)) <span class="sc">+</span></span>
<span id="cb345-3"><a href="solutions.html#cb345-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb345-4"><a href="solutions.html#cb345-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="fl">0.3</span>, <span class="dv">3</span>), <span class="at">name =</span> <span class="st">&quot;Ideological extremity&quot;</span>) <span class="sc">+</span></span>
<span id="cb345-5"><a href="solutions.html#cb345-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb345-6"><a href="solutions.html#cb345-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Relationship between age, climate change attitudes, </span><span class="sc">\n</span><span class="st"> and ideological extremity&quot;</span>,</span>
<span id="cb345-7"><a href="solutions.html#cb345-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Age&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Negative emotions about climate change&quot;</span>) <span class="sc">+</span></span>
<span id="cb345-8"><a href="solutions.html#cb345-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>sex, <span class="at">nrow=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="CPA-Seminar_files/figure-html/unnamed-chunk-147-1.png" width="672" /></p>
<p><em>Solution 2:</em></p>
<p>Alternatively, you might enjoy this look that you can create with <code>facet_grid()</code>:</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="solutions.html#cb346-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb346-2"><a href="solutions.html#cb346-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>age,<span class="at">y=</span>negemot, <span class="at">size=</span>ideology_ext, <span class="at">color =</span> Party)) <span class="sc">+</span></span>
<span id="cb346-3"><a href="solutions.html#cb346-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb346-4"><a href="solutions.html#cb346-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="fl">0.3</span>, <span class="dv">3</span>), <span class="at">name =</span> <span class="st">&quot;Ideological extremity&quot;</span>) <span class="sc">+</span></span>
<span id="cb346-5"><a href="solutions.html#cb346-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb346-6"><a href="solutions.html#cb346-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Relationship between age, climate change attitudes, and ideological extremity&quot;</span>,</span>
<span id="cb346-7"><a href="solutions.html#cb346-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Age&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Negative emotions about climate change&quot;</span>) <span class="sc">+</span></span>
<span id="cb346-8"><a href="solutions.html#cb346-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="fu">vars</span>(sex), <span class="fu">vars</span>(Party))</span></code></pre></div>
<p><img src="CPA-Seminar_files/figure-html/unnamed-chunk-148-1.png" width="672" /></p>
<p><em>Solution 3:</em></p>
<p>Or even this look, also done with <code>facet_grid()</code>:</p>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="solutions.html#cb347-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb347-2"><a href="solutions.html#cb347-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>age,<span class="at">y=</span>negemot, <span class="at">size=</span>ideology_ext, <span class="at">color =</span> Party)) <span class="sc">+</span></span>
<span id="cb347-3"><a href="solutions.html#cb347-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb347-4"><a href="solutions.html#cb347-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="fl">0.3</span>, <span class="dv">3</span>), <span class="at">name =</span> <span class="st">&quot;Ideological extremity&quot;</span>) <span class="sc">+</span></span>
<span id="cb347-5"><a href="solutions.html#cb347-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb347-6"><a href="solutions.html#cb347-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Relationship between age, climate change attitudes, and ideological extremity&quot;</span>,</span>
<span id="cb347-7"><a href="solutions.html#cb347-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Age&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Negative emotions about climate change&quot;</span>) <span class="sc">+</span></span>
<span id="cb347-8"><a href="solutions.html#cb347-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>sex <span class="sc">+</span> Party)</span></code></pre></div>
<p><img src="CPA-Seminar_files/figure-html/unnamed-chunk-149-1.png" width="672" /></p>
</div>
</div>
<div id="solutions-for-exercise-4" class="section level2 unnumbered">
<h2>Solutions for Exercise 4</h2>
<div id="task-1-9" class="section level3 unnumbered">
<h3>Task 1</h3>
<p>Let’s use the data set <em>glbwarm</em> again, which you should know well by now. Install / activate the <code>processR</code> package and assign the <em>glbwarm</em> data to a source object.</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="solutions.html#cb348-1" aria-hidden="true" tabindex="-1"></a><span class="co"># installing/loading the package:</span></span>
<span id="cb348-2"><a href="solutions.html#cb348-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(processR)) {</span>
<span id="cb348-3"><a href="solutions.html#cb348-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;processR&quot;</span>); </span>
<span id="cb348-4"><a href="solutions.html#cb348-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">require</span>(processR)</span>
<span id="cb348-5"><a href="solutions.html#cb348-5" aria-hidden="true" tabindex="-1"></a>} <span class="co">#load / install+load processR</span></span>
<span id="cb348-6"><a href="solutions.html#cb348-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb348-7"><a href="solutions.html#cb348-7" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> processR<span class="sc">::</span>glbwarm</span></code></pre></div>
<p>In this task, we want to tackle simple linear regression. More specifically, we want to predict the <em>ideology</em> of our respondents by their <em>age</em> because we assume that older respondents will hold more conservative viewpoints. The higher the values of the <em>ideology</em> variable, the more conservative the respondents are (coded from 1 ‘very liberal’ to 7 ‘very conservative’).</p>
<p><strong>Research question:</strong> Do older U.S. Americans hold more conservative viewpoints than younger U.S. Americans?</p>
<p>To answer this question, prepare a visual inspection of this relationship without fitting a regression line. Can you recognize a relationship? What is its nature?</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="solutions.html#cb349-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>ideology)) <span class="sc">+</span>                                         </span>
<span id="cb349-2"><a href="solutions.html#cb349-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_count</span>() <span class="sc">+</span>                                                                     </span>
<span id="cb349-3"><a href="solutions.html#cb349-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span>                                                                       </span>
<span id="cb349-4"><a href="solutions.html#cb349-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Age&quot;</span>, <span class="at">y=</span><span class="st">&quot;Conservatism&quot;</span>)</span></code></pre></div>
<p><img src="CPA-Seminar_files/figure-html/unnamed-chunk-151-1.png" width="672" /></p>
<p><strong>Evaluation:</strong> We can observe a small, positive relationship between age and conservatism. (This can be inferred from the amount of bigger bubbles clustering on the top right corner of the graph.)</p>
</div>
<div id="task-2-9" class="section level3 unnumbered">
<h3>Task 2</h3>
<p>Next, try to quantify the association using Pearson’s r. Interpret the result.</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="solutions.html#cb350-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(glbwarm<span class="sc">$</span>ideology,glbwarm<span class="sc">$</span>age, <span class="at">method=</span><span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  glbwarm$ideology and glbwarm$age
## t = 6.1978, df = 813, p-value = 0.0000000009096
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.1458602 0.2770376
## sample estimates:
##       cor 
## 0.2124056</code></pre>
<p><strong>Evaluation:</strong> There is a small, positive, and highly significant relationship between age and conservatism (r = 0.21, p &lt; 0.001). We can conclude that older U.S. Americans are more conservative.</p>
</div>
<div id="task-3-9" class="section level3 unnumbered">
<h3>Task 3</h3>
<p>Using your graph from Task 1, fit a regression line to your data points (<strong>Hint:</strong> You will need to load the <code>ggpubr</code> package). Interpret the parameters of the regression line.</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="solutions.html#cb352-1" aria-hidden="true" tabindex="-1"></a><span class="co"># installing/loading the package:</span></span>
<span id="cb352-2"><a href="solutions.html#cb352-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(ggpubr)) {</span>
<span id="cb352-3"><a href="solutions.html#cb352-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;ggpubr&quot;</span>); </span>
<span id="cb352-4"><a href="solutions.html#cb352-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">require</span>(ggpubr)</span>
<span id="cb352-5"><a href="solutions.html#cb352-5" aria-hidden="true" tabindex="-1"></a>} <span class="co">#load / install+load ggpubr</span></span></code></pre></div>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="solutions.html#cb353-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb353-2"><a href="solutions.html#cb353-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>ideology)) <span class="sc">+</span>                                         </span>
<span id="cb353-3"><a href="solutions.html#cb353-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_count</span>() <span class="sc">+</span>                                                                    </span>
<span id="cb353-4"><a href="solutions.html#cb353-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb353-5"><a href="solutions.html#cb353-5" aria-hidden="true" tabindex="-1"></a><span class="co">#  xlim(0,7) +</span></span>
<span id="cb353-6"><a href="solutions.html#cb353-6" aria-hidden="true" tabindex="-1"></a><span class="co">#  ylim(0,7.5) +</span></span>
<span id="cb353-7"><a href="solutions.html#cb353-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Age&quot;</span>, <span class="at">y=</span><span class="st">&quot;Conservatism&quot;</span>) <span class="sc">+</span> </span>
<span id="cb353-8"><a href="solutions.html#cb353-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&#39;lm&#39;</span>, <span class="at">formula=</span> y<span class="sc">~</span>x, <span class="at">color =</span> <span class="st">&quot;darkred&quot;</span>) <span class="sc">+</span></span>
<span id="cb353-9"><a href="solutions.html#cb353-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_cor</span>(<span class="fu">aes</span>(<span class="at">label =</span>  ..rr.label..)) <span class="sc">+</span> </span>
<span id="cb353-10"><a href="solutions.html#cb353-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_regline_equation</span>(<span class="at">label.y =</span> <span class="fl">6.2</span>)</span></code></pre></div>
<p><img src="CPA-Seminar_files/figure-html/unnamed-chunk-154-1.png" width="672" /></p>
<p><strong>Evaluation:</strong> The equation is Y = 3.1 + 0.02*X. This means that a person who becomes one year older is estimated to become 0.02 points more conservative. Similarly, two U.S. Americans with an age difference of 10 years are estimated to differ by 0.2 points on the ideology scale. However, age is not a really good predictor of conservatism as the predictor only explains about 4.5% of the observed variance in conservatism scores (R<sup>2</sup>).</p>
</div>
<div id="task-4-7" class="section level3 unnumbered">
<h3>Task 4</h3>
<p>Run a linear model in R using the <em>ideology</em> and <em>age</em> variables. Interpret the results.</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="solutions.html#cb354-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(ideology <span class="sc">~</span> age,<span class="at">data=</span>data))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ideology ~ age, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.7807 -0.8187  0.0647  0.8091  3.3793 
## 
## Coefficients:
##             Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept) 3.109423   0.165465  18.792 &lt; 0.0000000000000002 ***
## age         0.019663   0.003173   6.198        0.00000000091 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.478 on 813 degrees of freedom
## Multiple R-squared:  0.04512,    Adjusted R-squared:  0.04394 
## F-statistic: 38.41 on 1 and 813 DF,  p-value: 0.0000000009096</code></pre>
<p><strong>Evaluation:</strong> Again, we can extract the parameters for the intercept (<em>b<sub>[0]</sub></em> = 3.1), the regression coefficient (<em>b<sub>[1]</sub></em> = 0.019, <em>p</em> &lt; 0.001), and R<sup>2</sup> = 0.045. There is a significant, positive relationship between age and conservatism, but the effect is very small (size of <em>b<sub>[1]</sub></em>).</p>
</div>
<div id="task-5-7" class="section level3 unnumbered">
<h3>Task 5</h3>
<p>Since age alone does not seem to be a good predictor of conservatism, we want to introduce other predictors into the model and run a Multiple Linear Regression. This means that we will predict the effect of age on conservatism while controlling for the effect of third variables. For example, the respondents’ gender (<em>sex</em>, 0 = female, 1 = male) and their party preference (<em>partyid</em>, 1 = Democrat, 2 = Independent, 3 = Republican) might be great predictors of conservatism.</p>
<p><strong>Note:</strong> In a linear regression model, we can only include metric variables and variables that are binary coded (0/1). However, <em>partyid</em> is a categorical, i.e. factor variable, since Democrats are coded 1, Independents 2, and Republicans 3. Therefore, you need to mutate <em>partyid</em> and create two new binary variables <em>democrat</em> (0/1) and <em>republican</em> (0/1), where 1 indicates that the respondent identifies with that political party. (You don’t need to create a variable <em>independent</em>, since that information would be redundant: someone who has a value of 0 for both <em>republican</em> AND <em>democrat</em> MUST be an independent, so you can derive party preference with just two variables).</p>
<p>Then, run a multiple linear model that predicts <em>ideology</em> by <em>sex</em>, <em>democrat</em>, <em>republican</em>, and <em>age</em>. Interpret the results and the meaning of the age coefficient.</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="solutions.html#cb356-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb356-2"><a href="solutions.html#cb356-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">democrat =</span> <span class="fu">case_when</span>(</span>
<span id="cb356-3"><a href="solutions.html#cb356-3" aria-hidden="true" tabindex="-1"></a>    partyid <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb356-4"><a href="solutions.html#cb356-4" aria-hidden="true" tabindex="-1"></a>    partyid <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb356-5"><a href="solutions.html#cb356-5" aria-hidden="true" tabindex="-1"></a>    partyid <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb356-6"><a href="solutions.html#cb356-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">republican =</span> <span class="fu">case_when</span>(</span>
<span id="cb356-7"><a href="solutions.html#cb356-7" aria-hidden="true" tabindex="-1"></a>    partyid <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb356-8"><a href="solutions.html#cb356-8" aria-hidden="true" tabindex="-1"></a>    partyid <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb356-9"><a href="solutions.html#cb356-9" aria-hidden="true" tabindex="-1"></a>    partyid <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="dv">1</span>)</span>
<span id="cb356-10"><a href="solutions.html#cb356-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb356-11"><a href="solutions.html#cb356-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb356-12"><a href="solutions.html#cb356-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(ideology <span class="sc">~</span> sex <span class="sc">+</span> republican <span class="sc">+</span> democrat <span class="sc">+</span> age,<span class="at">data=</span>data))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ideology ~ sex + republican + democrat + age, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.0975 -0.9313  0.0256  0.7641  3.9739 
## 
## Coefficients:
##              Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)  3.504712   0.146041  23.998 &lt; 0.0000000000000002 ***
## sex          0.158677   0.083620   1.898             0.058105 .  
## republican   1.251718   0.113609  11.018 &lt; 0.0000000000000002 ***
## democrat    -0.848157   0.105368  -8.049  0.00000000000000296 ***
## age          0.009475   0.002610   3.630             0.000301 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.171 on 810 degrees of freedom
## Multiple R-squared:  0.4031, Adjusted R-squared:  0.4002 
## F-statistic: 136.8 on 4 and 810 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p><strong>Evaluation:</strong> Compared to our simple model, the R<sup>2</sup> has increased dramatically, from 0.045 to 0.403! We can now explain 40.3% of the variance in conservatism with the newly introduced covariates. While gender is not a significant predictor of conservatism (<em>b<sub>[1]</sub></em> = 0.158, p = 0.058), i.e., there is no significant difference in conservatism between men and women, party preference plays a large role in explaining conservative viewpoints. Republicans are more conservative (<em>b<sub>[2]</sub></em> = 1.251, p &lt; 0.001) than Independents (reference category, not included as a separate variable), while Democrats are less conservative than Independents (<em>b<sub>[3]</sub></em> = -0.848, p &lt; 0.001). The size of the effect that age has on conservatism has decreased further now that we control for sex and party preference (<em>b<sub>[4]</sub></em> = 0.009, p &lt; 0.001). This implies that some of the effects of age are now transported through sex and, more likely, party preference. We can conclude that two U.S. citizens who differ by 10 years but have the same gender and party preference are estimated to differ by 0.09 points on the conservatism scale. That’s a really small effect, but it’s still significant.</p>
</div>
<div id="task-6-5" class="section level3 unnumbered">
<h3>Task 6</h3>
<p>Standardize all relevant variables and run the model again (note that binary variables shouldn’t be standardized). How does the interpretation of the age coefficient change?</p>
<p><em>Solution:</em></p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="solutions.html#cb358-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>ideology_st <span class="ot">&lt;-</span> <span class="fu">scale</span>(data<span class="sc">$</span>ideology)</span>
<span id="cb358-2"><a href="solutions.html#cb358-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>age_st <span class="ot">&lt;-</span> <span class="fu">scale</span>(data<span class="sc">$</span>age)</span>
<span id="cb358-3"><a href="solutions.html#cb358-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb358-4"><a href="solutions.html#cb358-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(ideology_st <span class="sc">~</span> sex <span class="sc">+</span> republican <span class="sc">+</span> democrat <span class="sc">+</span> age_st,<span class="at">data=</span>data))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ideology_st ~ sex + republican + democrat + age_st, 
##     data = data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.71045 -0.61607  0.01696  0.50543  2.62866 
## 
## Coefficients:
##             Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept) -0.07233    0.06386  -1.133             0.257702    
## sex          0.10496    0.05531   1.898             0.058105 .  
## republican   0.82799    0.07515  11.018 &lt; 0.0000000000000002 ***
## democrat    -0.56104    0.06970  -8.049  0.00000000000000296 ***
## age_st       0.10236    0.02819   3.630             0.000301 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.7745 on 810 degrees of freedom
## Multiple R-squared:  0.4031, Adjusted R-squared:  0.4002 
## F-statistic: 136.8 on 4 and 810 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p><strong>Evaluation:</strong> The age coefficient is now expressed in standard deviations from the mean: Two U.S. Americans with one standard deviation difference in their age are expected to rank <em>b<sub>[4]</sub></em> = 0.102 (p &lt; 0.001) standard deviations higher on the conservatism scale, when controlling for the influence of sex and party preference. If we had a second standardized coefficient in the model, then we could compare their effect sizes directly.</p>
</div>
</div>
<div id="solutions-for-exercise-5" class="section level2 unnumbered">
<h2>Solutions for Exercise 5</h2>
<p>In this Exercise, we will work with the <em>pmi</em> datatset. It’s a data set of a communication science experiment that was conducted by Tal-Or, Cohen, Tsfati, &amp; Gunther in 2010 and comes pre-installed with <code>processR</code>. The data set contains 123 observations of 6 variables. There are three variables of interest to us in this data set:</p>
<ol style="list-style-type: decimal">
<li><p><strong>cond:</strong> article about sugar shortage was placed at the front (1) or interior (0) page of a newspaper</p></li>
<li><p><strong>pmi</strong>: belief that others will be prompted to buy sugar as a result of exposure to the article (scale: 1-7)</p></li>
<li><p><strong>reaction:</strong> intention to buy sugar (scale: 1-7)</p></li>
</ol>
<p>Let’s load <code>processR</code> and save the <em>pmi</em> data to a source object called <em>data</em>:</p>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb360-1"><a href="solutions.html#cb360-1" aria-hidden="true" tabindex="-1"></a><span class="co"># installing/loading the package:</span></span>
<span id="cb360-2"><a href="solutions.html#cb360-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(processR)) {</span>
<span id="cb360-3"><a href="solutions.html#cb360-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;processR&quot;</span>); </span>
<span id="cb360-4"><a href="solutions.html#cb360-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">require</span>(processR)</span>
<span id="cb360-5"><a href="solutions.html#cb360-5" aria-hidden="true" tabindex="-1"></a>} <span class="co">#load / install+load processR</span></span>
<span id="cb360-6"><a href="solutions.html#cb360-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb360-7"><a href="solutions.html#cb360-7" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> processR<span class="sc">::</span>pmi</span></code></pre></div>
<p>The <strong>theory of presumed media influence</strong> suggests that people perceive some effect of a message on others and then react to that perception. Based on this theory, we assume that when the sugar article appears on the front page, the reader will be more likely to believe that others will be prompted to buy sugar. Therefore, the reader will act on this belief and show greater intention to buy sugar themselves (to avoid a personal shortage because others are buying sugar).</p>
<p><strong>Research Question:</strong> Is the effect of article placement (front/interior) on the intention to buy sugar mediated by the belief that others will be prompted to buy sugar as a result of exposure to the article? That is, do participants who take part in the front-page experimental condition develop a greater belief that others will be prompted to buy sugar, while this belief increases their own intention to buy sugar?</p>
<div id="task-1-10" class="section level3 unnumbered">
<h3>Task 1</h3>
<p><strong>What variables are X, Y, and M in this scenario? Write it down.</strong></p>
<p>X = <em>cond</em>; article about sugar shortage was placed at the front (1) or interior (0) page of a newspaper</p>
<p>Y = <em>reaction</em>; intention to buy sugar (scale: 1-7)</p>
<p>M = <em>pmi</em>; belief that others will be prompted to buy sugar as a result of exposure to the article (scale: 1-7)</p>
</div>
<div id="task-2-10" class="section level3 unnumbered">
<h3>Task 2</h3>
<p><strong>Create three plots:</strong></p>
<ol style="list-style-type: decimal">
<li><p>The effect <em>c</em> of X on Y without controlling for M.</p></li>
<li><p>The direct effect <em>a</em> of X on M.</p></li>
<li><p>The effect of M on Y without controlling for X.</p></li>
</ol>
<p><strong>Evaluate the plots. What do they tell you?</strong></p>
<ol style="list-style-type: decimal">
<li>The effect <em>c</em> of X on Y without controlling for M:</li>
</ol>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="solutions.html#cb361-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb361-2"><a href="solutions.html#cb361-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cond =</span> <span class="fu">case_when</span>(</span>
<span id="cb361-3"><a href="solutions.html#cb361-3" aria-hidden="true" tabindex="-1"></a>    cond <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">&quot;interior page&quot;</span>,</span>
<span id="cb361-4"><a href="solutions.html#cb361-4" aria-hidden="true" tabindex="-1"></a>    cond <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">&quot;front page&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb361-5"><a href="solutions.html#cb361-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>cond, <span class="at">y=</span>reaction)) <span class="sc">+</span></span>
<span id="cb361-6"><a href="solutions.html#cb361-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">fill =</span> cond), <span class="at">fun=</span>mean, <span class="at">geom=</span><span class="st">&quot;bar&quot;</span>) <span class="sc">+</span></span>
<span id="cb361-7"><a href="solutions.html#cb361-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">round</span>(..y..,<span class="dv">2</span>)), <span class="at">fun=</span>mean, <span class="at">geom=</span><span class="st">&quot;text&quot;</span>, <span class="at">size=</span><span class="dv">6</span>,</span>
<span id="cb361-8"><a href="solutions.html#cb361-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">vjust =</span> <span class="fl">1.2</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb361-9"><a href="solutions.html#cb361-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb361-10"><a href="solutions.html#cb361-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb361-11"><a href="solutions.html#cb361-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Experimental condition&quot;</span>, <span class="at">y=</span><span class="st">&quot;Intention to buy sugar&quot;</span>, <span class="at">title=</span><span class="st">&quot;Figure 1&quot;</span>)</span></code></pre></div>
<p><img src="CPA-Seminar_files/figure-html/unnamed-chunk-159-1.png" width="672" /></p>
<ol start="2" style="list-style-type: decimal">
<li>The direct effect <em>a</em> of X on M:</li>
</ol>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb362-1"><a href="solutions.html#cb362-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb362-2"><a href="solutions.html#cb362-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cond =</span> <span class="fu">case_when</span>(</span>
<span id="cb362-3"><a href="solutions.html#cb362-3" aria-hidden="true" tabindex="-1"></a>    cond <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">&quot;interior page&quot;</span>,</span>
<span id="cb362-4"><a href="solutions.html#cb362-4" aria-hidden="true" tabindex="-1"></a>    cond <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">&quot;front page&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb362-5"><a href="solutions.html#cb362-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>cond, <span class="at">y=</span>pmi)) <span class="sc">+</span></span>
<span id="cb362-6"><a href="solutions.html#cb362-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">fill =</span> cond), <span class="at">fun=</span>mean, <span class="at">geom=</span><span class="st">&quot;bar&quot;</span>) <span class="sc">+</span></span>
<span id="cb362-7"><a href="solutions.html#cb362-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">round</span>(..y..,<span class="dv">2</span>)), <span class="at">fun=</span>mean, <span class="at">geom=</span><span class="st">&quot;text&quot;</span>, <span class="at">size=</span><span class="dv">6</span>,</span>
<span id="cb362-8"><a href="solutions.html#cb362-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">vjust =</span> <span class="fl">1.2</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb362-9"><a href="solutions.html#cb362-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb362-10"><a href="solutions.html#cb362-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb362-11"><a href="solutions.html#cb362-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Experimental condition&quot;</span>, <span class="at">y=</span><span class="st">&quot;Belief that others will be prompted to buy sugar</span><span class="sc">\n</span><span class="st"> as a result of exposure to the article&quot;</span>, <span class="at">title=</span><span class="st">&quot;Figure 2&quot;</span>)</span></code></pre></div>
<p><img src="CPA-Seminar_files/figure-html/unnamed-chunk-160-1.png" width="672" /></p>
<ol start="3" style="list-style-type: decimal">
<li>The effect of M on Y without controlling for X:</li>
</ol>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="solutions.html#cb363-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb363-2"><a href="solutions.html#cb363-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>pmi, <span class="at">y=</span>reaction)) <span class="sc">+</span>                                         </span>
<span id="cb363-3"><a href="solutions.html#cb363-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_count</span>() <span class="sc">+</span>                                                                     </span>
<span id="cb363-4"><a href="solutions.html#cb363-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span>                                                                       </span>
<span id="cb363-5"><a href="solutions.html#cb363-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Belief that others will be prompted to buy sugar</span><span class="sc">\n</span><span class="st"> as a result of exposure to the article&quot;</span>, <span class="at">y=</span><span class="st">&quot;Intention to buy sugar&quot;</span>, <span class="at">title=</span><span class="st">&quot;Figure 3&quot;</span>)</span></code></pre></div>
<p><img src="CPA-Seminar_files/figure-html/unnamed-chunk-161-1.png" width="672" /></p>
<p><strong>Evaluation:</strong> Visually, there seems to be an effect at play in all three plots. The intention to buy sugar is higher in the front page condition (Figure 1). Moreover, the belief that others will be prompted to buy sugar as a result of exposure to the article is higher in the front page experimental condition (Figure 2). And we can assume that participants who hold stronger beliefs that others will be prompted to buy sugar will act on this belief and show greater intention to buy sugar themselves (Figure 3).</p>
</div>
<div id="task-3-10" class="section level3 unnumbered">
<h3>Task 3</h3>
<p><strong>Fit two linear regression models that…</strong></p>
<ol style="list-style-type: decimal">
<li><p>quantify the direct effect <em>a</em> of X on M.</p></li>
<li><p>quantify the direct effect <em>c’</em> of X on Y while controlling for M AND the direct effect <em>b</em> of M on Y while controlling for X.</p></li>
</ol>
<p><strong>Evaluate both models. What are the regression equations of these models? And how do you interpret their regression coefficients?</strong></p>
<ol style="list-style-type: decimal">
<li>Quantify the direct effect <em>a</em> of X on M:</li>
</ol>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="solutions.html#cb364-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(pmi <span class="sc">~</span> cond, <span class="at">data=</span>data))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = pmi ~ cond, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8534 -0.8534  0.1466  1.1231  1.6231 
## 
## Coefficients:
##             Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept)   5.3769     0.1618  33.222 &lt;0.0000000000000002 ***
## cond          0.4765     0.2357   2.022              0.0454 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.305 on 121 degrees of freedom
## Multiple R-squared:  0.03268,    Adjusted R-squared:  0.02468 
## F-statistic: 4.088 on 1 and 121 DF,  p-value: 0.0454</code></pre>
<p><strong>Evaluation:</strong> The regression equation is M = i<sub>[M]</sub> + a * X, where <em>i<sub>[M]</sub></em> = 5.376 and <em>a</em> = 0.476, i.e. M = 5.376 + 0.476 * X.</p>
<p>Interpretation of <em>i<sub>[M]</sub></em> = 5.376: This is the intercept.</p>
<p>Interpretation of <em>a</em> = 0.476: Two participants who differ by one unit on X are expected to differ by <em>a</em> = 0.476 units on M. Since <em>a</em> is positive, we can conclude that participants who are part of the front page condition (X = 1) will have a 0.477 units <em>higher</em> belief that others will be prompted to buy sugar as a result of exposure to the article than those assigned to the interior page condition (X = 0).</p>
<ol start="2" style="list-style-type: decimal">
<li>Quantify the direct effect <em>c’</em> of X on Y while controlling for M AND the direct effect <em>b</em> of M on Y while controlling for X</li>
</ol>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="solutions.html#cb366-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(reaction <span class="sc">~</span> cond <span class="sc">+</span> pmi, <span class="at">data=</span>data))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = reaction ~ cond + pmi, data = data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -3.07636 -1.06128 -0.06346  0.94573  2.94299 
## 
## Coefficients:
##             Estimate Std. Error t value    Pr(&gt;|t|)    
## (Intercept)  0.52687    0.54968   0.958       0.340    
## cond         0.25435    0.25582   0.994       0.322    
## pmi          0.50645    0.09705   5.219 0.000000766 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.393 on 120 degrees of freedom
## Multiple R-squared:  0.2059, Adjusted R-squared:  0.1927 
## F-statistic: 15.56 on 2 and 120 DF,  p-value: 0.000000983</code></pre>
<p><strong>Evaluation:</strong> The regression equation is Y = i<sub>[Y]</sub> + c′ * X + b * M, where <em>i<sub>[Y]</sub></em> = 0.526, <em>c′</em> = 0.254, and <em>b</em> = 0.506, i.e. Y = 0.526 + 0.254 * X + 0.506 * M.</p>
<p>Interpretation of <em>i<sub>[Y]</sub></em> = 0.526: This is the intercept.</p>
<p>Interpretation of <em>c′</em> = 0.254: The effect <em>c′</em> is not significant, so we should not interpret it. For the sake of practice, this time, we should do it anyway. Two participants who differ by one unit on X but are equal on M are estimated to differ by 0.254 units on Y. This means that participants who share equal beliefs that others will be prompted to buy sugar as a result of exposure to the article, but one is part of the front page condition (X = 1) and the other is part of the interior page condition (X = 0), are estimated to differ by 0.254 units on average in their intentions to buy sugar. Since <em>c′</em> is positive, participants assigned to the front page condition (X = 1) are estimated to be 0.254 units higher than those who are part of interior page condition.</p>
<p>Interpretation of <em>b</em> = 0.506: Two participants who were assigned to the same experimental condition (i.e., equal on X) but who differ by one unit in their belief that others will be prompted to buy sugar as a result of exposure to the article (M) are estimated to differ by 0.506 units in intention to buy sugar. Because <em>b</em> is positive, participants with a higher level of presumed media influence are expected to have higher sugar purchasing intentions.</p>
</div>
<div id="task-4-8" class="section level3 unnumbered">
<h3>Task 4</h3>
<p><strong>Calculate and interpret the indirect effect <em>ab</em>.</strong></p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="solutions.html#cb368-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ab <span class="ot">&lt;-</span> <span class="fl">0.476</span><span class="sc">*</span><span class="fl">0.506</span>)</span></code></pre></div>
<pre><code>## [1] 0.240856</code></pre>
<p><strong>Evaluation:</strong> As a result of the effect of article placement on the belief that others would be encouraged to purchase sugar, which in turn influenced participants’ own purchase intentions, participants who read an article on the front page of the newspaper were 0.241 units more likely to purchase sugar than those who read it on the interior page.</p>
</div>
<div id="task-5-8" class="section level3 unnumbered">
<h3>Task 5</h3>
<p><strong>Calculate and interpret the total effect <em>c</em>.</strong></p>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="solutions.html#cb370-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(reaction <span class="sc">~</span> cond, <span class="at">data=</span>data))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = reaction ~ cond, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.4957 -1.0000 -0.2457  1.2543  3.5000 
## 
## Coefficients:
##             Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept)   3.2500     0.1906  17.052 &lt;0.0000000000000002 ***
## cond          0.4957     0.2775   1.786              0.0766 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.537 on 121 degrees of freedom
## Multiple R-squared:  0.02568,    Adjusted R-squared:  0.01763 
## F-statistic:  3.19 on 1 and 121 DF,  p-value: 0.07661</code></pre>
<p>The total effect is <em>c</em> = <em>c′</em> + <em>ab</em> = 0.254 + 0.241 = 0.495, which is the regression coefficient of <em>cond</em> in the above equation.</p>
<p><strong>Evaluation:</strong> Participants who read the article on the front page had, on average, 0.495 units <em>greater</em> intention to buy sugar than those who read the article on the interior page of the newspaper.</p>
</div>
<div id="task-6-6" class="section level3 unnumbered">
<h3>Task 6</h3>
<p><strong>Now run the same analysis, but use <code>processR</code> (i.e., the <code>process</code> function). Only look at the <code>process</code> output and write down the coefficients <em>a</em>, <em>b</em>, <em>c’</em>, <em>ab</em>, and <em>c</em>.</strong></p>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="solutions.html#cb372-1" aria-hidden="true" tabindex="-1"></a><span class="fu">process</span>(<span class="at">data=</span>data, <span class="at">y=</span><span class="st">&quot;reaction&quot;</span>, <span class="at">x=</span><span class="st">&quot;cond&quot;</span>, <span class="at">m=</span><span class="st">&quot;pmi&quot;</span>, </span>
<span id="cb372-2"><a href="solutions.html#cb372-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">total=</span><span class="dv">1</span>, <span class="co"># calculate the total effect</span></span>
<span id="cb372-3"><a href="solutions.html#cb372-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">normal=</span><span class="dv">1</span>, <span class="co"># calculate p-values with standard normal distribution</span></span>
<span id="cb372-4"><a href="solutions.html#cb372-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">model=</span><span class="dv">4</span>, <span class="co"># run a simple mediation</span></span>
<span id="cb372-5"><a href="solutions.html#cb372-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">seed=</span><span class="dv">42</span> <span class="co"># insert a number of your liking</span></span>
<span id="cb372-6"><a href="solutions.html#cb372-6" aria-hidden="true" tabindex="-1"></a>         )</span></code></pre></div>
<p><img src="images/Tut14_processR_1.JPG" />
<img src="images/Tut14_processR_2.JPG" /></p>
</div>
<div id="task-7-3" class="section level3 unnumbered">
<h3>Task 7</h3>
<p><strong>Finally, create a diagram that displays the results of your analysis.</strong></p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb373-1"><a href="solutions.html#cb373-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb373-2"><a href="solutions.html#cb373-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb373-3"><a href="solutions.html#cb373-3" aria-hidden="true" tabindex="-1"></a>labels <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">X=</span><span class="st">&quot;cond&quot;</span>,<span class="at">M=</span><span class="st">&quot;pmi&quot;</span>,<span class="at">Y=</span><span class="st">&quot;reaction&quot;</span>)</span>
<span id="cb373-4"><a href="solutions.html#cb373-4" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">tripleEquation</span>(<span class="at">X=</span><span class="st">&quot;cond&quot;</span>,<span class="at">M=</span><span class="st">&quot;pmi&quot;</span>,<span class="at">Y=</span><span class="st">&quot;reaction&quot;</span>)</span>
<span id="cb373-5"><a href="solutions.html#cb373-5" aria-hidden="true" tabindex="-1"></a>semfit <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="at">model=</span>model,<span class="at">data=</span>data)</span>
<span id="cb373-6"><a href="solutions.html#cb373-6" aria-hidden="true" tabindex="-1"></a><span class="fu">statisticalDiagram</span>(<span class="dv">4</span>,<span class="at">labels=</span>labels,<span class="at">fit=</span>semfit,<span class="at">whatLabel=</span><span class="st">&quot;est&quot;</span>)</span></code></pre></div>
<p><img src="CPA-Seminar_files/figure-html/unnamed-chunk-167-1.png" width="672" /></p>
</div>
</div>
<div id="solutions-for-exercise-6" class="section level2 unnumbered">
<h2>Solutions for Exercise 6</h2>
<p>In this Exercise, we will work with the <em>disaster</em> datatset. It’s a data set of a communication science experiment that was conducted by Chapman and Lickel in 2016 and comes pre-installed with <code>processR</code>. The data set contains 211 observations of 5 variables and investigates how framing of climate change disasters affects justifications for giving or withholding aid to disaster victims. There are three variables of interest to us in this data set:</p>
<ol style="list-style-type: decimal">
<li><p><strong>frame:</strong> article was framed as a naturally caused disaster (0) or article was framed as a climate change caused disaster (1)</p></li>
<li><p><strong>skeptic</strong>: climate change skepticism, higher scores indicate greater skepticism about the reality of climate change (scale: 1-9)</p></li>
<li><p><strong>justify:</strong> strength of a participant’s justifications for withholding aid, higher scores indicate a stronger sense that helping out the victims is not justified (scale: 1-7)</p></li>
</ol>
<p>Let’s load <code>processR</code> and save the <em>disaster</em> data to a source object called <em>data</em>:</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="solutions.html#cb374-1" aria-hidden="true" tabindex="-1"></a><span class="co"># installing/loading the package:</span></span>
<span id="cb374-2"><a href="solutions.html#cb374-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(processR)) {</span>
<span id="cb374-3"><a href="solutions.html#cb374-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">&quot;processR&quot;</span>); </span>
<span id="cb374-4"><a href="solutions.html#cb374-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">require</span>(processR)</span>
<span id="cb374-5"><a href="solutions.html#cb374-5" aria-hidden="true" tabindex="-1"></a>} <span class="co">#load / install+load processR</span></span>
<span id="cb374-6"><a href="solutions.html#cb374-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb374-7"><a href="solutions.html#cb374-7" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> processR<span class="sc">::</span>disaster</span></code></pre></div>
<p><strong>Framing theory</strong> suggests that the way a topic is presented to the audience (referred to as “frame”) affects how individuals interpret that information and thus evaluate the topic.</p>
<p><strong>Research Question:</strong> Does framing a disaster as caused by climate change, rather than leaving the cause undetermined, affect people’s justification for not helping, and does this framing effect depend on people’s skepticism about climate change?</p>
<div id="task-1-11" class="section level3 unnumbered">
<h3>Task 1</h3>
<p><strong>What variables are X, Y, and W in this scenario? Write it down.</strong></p>
<p>X = <em>frame:</em>; article was framed as a naturally caused disaster (0) or article was framed as a climate change caused disaster (0)</p>
<p>Y = <em>justify</em>; strength of a participant’s justifications for withholding aid to drought victims, higher scores indicate a stronger sense that helping out the victims is not justified (scale: 1-7)</p>
<p>W = <em>skeptic</em>; climate change skepticism, higher scores indicate greater skepticism about the reality of climate change (scale: 1-9)</p>
</div>
<div id="task-2-11" class="section level3 unnumbered">
<h3>Task 2</h3>
<p><strong>Investigate the relationship between X and Y with a plot. Next, make a visual check if this effect depends on different levels of W. Finally, evaluate the figures.</strong></p>
<p>There are many options to visualize the effects and a lot of these approaches are covered in [Moderation Analysis]. Here, we’ll use bar charts.</p>
<ol style="list-style-type: decimal">
<li>The effect of X on Y:</li>
</ol>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb375-1"><a href="solutions.html#cb375-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb375-2"><a href="solutions.html#cb375-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">frame =</span> <span class="fu">case_when</span>(</span>
<span id="cb375-3"><a href="solutions.html#cb375-3" aria-hidden="true" tabindex="-1"></a>    frame <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">&quot;naturally caused drought&quot;</span>,</span>
<span id="cb375-4"><a href="solutions.html#cb375-4" aria-hidden="true" tabindex="-1"></a>    frame <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">&quot;drought caused by climate change&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb375-5"><a href="solutions.html#cb375-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>frame, <span class="at">y=</span>justify)) <span class="sc">+</span></span>
<span id="cb375-6"><a href="solutions.html#cb375-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">fill =</span> frame), <span class="at">fun=</span>mean, <span class="at">geom=</span><span class="st">&quot;bar&quot;</span>) <span class="sc">+</span></span>
<span id="cb375-7"><a href="solutions.html#cb375-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">round</span>(..y..,<span class="dv">2</span>)), <span class="at">fun=</span>mean, <span class="at">geom=</span><span class="st">&quot;text&quot;</span>, <span class="at">size=</span><span class="dv">6</span>,</span>
<span id="cb375-8"><a href="solutions.html#cb375-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">vjust =</span> <span class="fl">1.2</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb375-9"><a href="solutions.html#cb375-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb375-10"><a href="solutions.html#cb375-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb375-11"><a href="solutions.html#cb375-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Experimental condition&quot;</span>, <span class="at">y=</span><span class="st">&quot;Justifications to withhold aid to drought victims&quot;</span>, <span class="at">title=</span><span class="st">&quot;Figure 1&quot;</span>)</span></code></pre></div>
<p><img src="CPA-Seminar_files/figure-html/unnamed-chunk-169-1.png" width="672" /></p>
<ol start="2" style="list-style-type: decimal">
<li>The effect of X on Y on different levels of W:</li>
</ol>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="solutions.html#cb376-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb376-2"><a href="solutions.html#cb376-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">frame =</span> <span class="fu">case_when</span>(</span>
<span id="cb376-3"><a href="solutions.html#cb376-3" aria-hidden="true" tabindex="-1"></a>    frame <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">&quot;naturally caused drought&quot;</span>,</span>
<span id="cb376-4"><a href="solutions.html#cb376-4" aria-hidden="true" tabindex="-1"></a>    frame <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">&quot;drought caused by climate change&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb376-5"><a href="solutions.html#cb376-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">skeptic_fct =</span> <span class="fu">case_when</span>(</span>
<span id="cb376-6"><a href="solutions.html#cb376-6" aria-hidden="true" tabindex="-1"></a>    skeptic <span class="sc">&gt;=</span> <span class="fl">6.0</span> <span class="sc">~</span> <span class="st">&quot;high skepticism&quot;</span>,</span>
<span id="cb376-7"><a href="solutions.html#cb376-7" aria-hidden="true" tabindex="-1"></a>    skeptic <span class="sc">&gt;=</span> <span class="fl">3.0</span> <span class="sc">~</span> <span class="st">&quot;medium skepticism&quot;</span>,</span>
<span id="cb376-8"><a href="solutions.html#cb376-8" aria-hidden="true" tabindex="-1"></a>    skeptic <span class="sc">&lt;</span> <span class="fl">3.0</span> <span class="sc">~</span> <span class="st">&quot;low skepticism&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb376-9"><a href="solutions.html#cb376-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">skeptic_fct =</span> <span class="fu">factor</span>(skeptic_fct, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;low skepticism&quot;</span>,<span class="st">&quot;medium skepticism&quot;</span>,<span class="st">&quot;high skepticism&quot;</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb376-10"><a href="solutions.html#cb376-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>frame, <span class="at">y=</span>justify)) <span class="sc">+</span></span>
<span id="cb376-11"><a href="solutions.html#cb376-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">fill =</span> frame), <span class="at">fun=</span>mean, <span class="at">geom=</span><span class="st">&quot;bar&quot;</span>) <span class="sc">+</span></span>
<span id="cb376-12"><a href="solutions.html#cb376-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">round</span>(..y..,<span class="dv">2</span>)), <span class="at">fun=</span>mean, <span class="at">geom=</span><span class="st">&quot;text&quot;</span>, <span class="at">size=</span><span class="dv">4</span>,</span>
<span id="cb376-13"><a href="solutions.html#cb376-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">vjust =</span> <span class="fl">1.2</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb376-14"><a href="solutions.html#cb376-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb376-15"><a href="solutions.html#cb376-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">legend.title=</span><span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb376-16"><a href="solutions.html#cb376-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),</span>
<span id="cb376-17"><a href="solutions.html#cb376-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb376-18"><a href="solutions.html#cb376-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Experimental condition:&quot;</span>, <span class="at">y=</span><span class="st">&quot;Justifications to withhold aid to drought victims&quot;</span>, <span class="at">title=</span><span class="st">&quot;Figure 2&quot;</span>) <span class="sc">+</span></span>
<span id="cb376-19"><a href="solutions.html#cb376-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>skeptic_fct)</span></code></pre></div>
<p><img src="CPA-Seminar_files/figure-html/unnamed-chunk-170-1.png" width="672" /></p>
<p><strong>Evaluation:</strong> Figure 1 shows that participants who read a report attributing droughts to climate change indicated a stronger justification for withholding aid (Ȳ = 2.94) than those who did not receive such a reference (Ȳ = 2.80). Figure 2 illustrates that the attribution of cause affects people differently depending on their opinions about the reality of climate change, implying that climate change skepticism moderates the effect of the ascribed cause of the drought. It appears that participants who have lower climate change skepticism scores report weaker justifications for withholding aid when told the drought was caused by climate change compared to when not so told. The opposite is true among people who rate high in climate change skepticism.</p>
</div>
<div id="task-3-11" class="section level3 unnumbered">
<h3>Task 3</h3>
<p><strong>Run a linear regression model that includes an interaction term of X and M. Note down the regression equation and interpret the coefficients.</strong></p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb377-1"><a href="solutions.html#cb377-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(justify <span class="sc">~</span> frame<span class="sc">+</span>skeptic<span class="sc">+</span>frame<span class="sc">*</span>skeptic,<span class="at">data=</span>data))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = justify ~ frame + skeptic + frame * skeptic, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.1267 -0.5864 -0.0117  0.5084  2.5484 
## 
## Coefficients:
##               Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)    2.45153    0.14904  16.449 &lt; 0.0000000000000002 ***
## frame         -0.56247    0.21792  -2.581             0.010539 *  
## skeptic        0.10508    0.03813   2.756             0.006375 ** 
## frame:skeptic  0.20118    0.05527   3.640             0.000344 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8129 on 207 degrees of freedom
## Multiple R-squared:  0.2463, Adjusted R-squared:  0.2353 
## F-statistic: 22.54 on 3 and 207 DF,  p-value: 0.000000000001138</code></pre>
<p><strong>Evaluation:</strong> The regression equation is Y = i<sub>[Y]</sub> + b<sub>1</sub> * X + b<sub>2</sub> * W + b<sub>3</sub> * XW, where <em>i<sub>[Y]</sub></em> = 2.451, <em>b<sub>1</sub></em> = -0.562, <em>b<sub>2</sub></em> = 0.105, and <em>b<sub>3</sub></em> = 0.201. I.e., Y = 2.451 -0.562 * X + 0.105 * W + 0.201 * XW.</p>
<p><em>b<sub>1</sub></em> = -0.562 (<em>p</em> &lt; .05) indicates the difference between the group means of those who were told that the drought was caused by climate change and those who were, given that climate change skepticism scores 0 in both groups (W = 0, not a valid value and nonsensical!). You can also say that two participants who differ by one unit on X, but rate 0 on W, are estimated to differ by -0.562 units on Y. That is, participants who rate 0 on climate change skepticism (again: not a valid value and nonsensical!) and were told that the drought was naturally caused are estimated to rate 2.451 on Y (intercept), while participants who rate 0 on climate change skepticism (again: not a valid value and nonsensical!) and were told that the drought was caused by climate change are estimated to rate 1,889 on Y.</p>
<p><em>b<sub>2</sub></em> = 0.105 (<em>p</em> &lt; .01) indicates the estimated change on Y for two participants who differ by one unit on M, but rate 0 on X. That is, two participants who differ by one unit in their climate change skepticism but were both told that the drought had a natural cause are estimated to be 0.105 units more likely to justify to withhold aid to drought victims.</p>
<p><em>b<sub>3</sub></em> = 0.201 is statistically different from 0 (<em>p</em> &lt; .001), which means that the effect of framing on justifications to withdraw aid for drought victims depends on people’s skepticism about climate change. Moreover, <em>b<sub>3</sub></em> quantifies how the effect of X on Y changes as W changes by one unit. That is, as climate change skepticism increases by one unit, the difference in strength of justifications between those told climate change was the cause and those not so told “increases” by 0.201 units.</p>
</div>
<div id="task-4-9" class="section level3 unnumbered">
<h3>Task 4</h3>
<p><strong>Mean-center the climate change skepticism variable and run the model again. How does the interpretation of <em>b<sub>1</sub></em> change?</strong></p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb379-1"><a href="solutions.html#cb379-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>skeptic_mc <span class="ot">&lt;-</span> <span class="fu">scale</span>(data<span class="sc">$</span>skeptic, <span class="at">center=</span><span class="cn">TRUE</span>, <span class="at">scale=</span><span class="cn">FALSE</span>)</span>
<span id="cb379-2"><a href="solutions.html#cb379-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb379-3"><a href="solutions.html#cb379-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(justify <span class="sc">~</span> frame<span class="sc">+</span>skeptic_mc<span class="sc">+</span>frame<span class="sc">*</span>skeptic_mc,<span class="at">data=</span>data))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = justify ~ frame + skeptic_mc + frame * skeptic_mc, 
##     data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.1267 -0.5864 -0.0117  0.5084  2.5484 
## 
## Coefficients:
##                  Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)       2.80650    0.07753  36.201 &lt; 0.0000000000000002 ***
## frame             0.11712    0.11206   1.045             0.297156    
## skeptic_mc        0.10508    0.03813   2.756             0.006375 ** 
## frame:skeptic_mc  0.20118    0.05527   3.640             0.000344 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8129 on 207 degrees of freedom
## Multiple R-squared:  0.2463, Adjusted R-squared:  0.2353 
## F-statistic: 22.54 on 3 and 207 DF,  p-value: 0.000000000001138</code></pre>
<p><strong>Evaluation:</strong> The reparameterization did change <em>b<sub>1</sub></em> = 0.117 and its meaning. Actually, the conditional effect <em>b<sub>1</sub></em> is not nonsensical anymore! You can now interpret scores of W = 0 as the mean because now W = 0 when W = mean(W) = 3.377. <em>b<sub>1</sub></em> now estimates the difference in strength of justifications for withholding aid between those told climate change caused the drought and those not so told among those with <em>average</em> climate change skepticism. Participants who rate 0, i.e. average, on climate change skepticism and were told that the drought was naturally caused are estimated to rate 2.806 on Y (intercept), while participants who rate 0, i.e. average, on climate change skepticism and were told that the drought was caused by climate change are estimated to rate 2.806 + 0.117 = 2.923 on Y.</p>
</div>
<div id="task-5-9" class="section level3 unnumbered">
<h3>Task 5</h3>
<p><strong>Probe the interaction.</strong></p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb381-1"><a href="solutions.html#cb381-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(interactions)</span>
<span id="cb381-2"><a href="solutions.html#cb381-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb381-3"><a href="solutions.html#cb381-3" aria-hidden="true" tabindex="-1"></a>intrct_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(justify <span class="sc">~</span> frame<span class="sc">+</span>skeptic_mc<span class="sc">+</span>frame<span class="sc">*</span>skeptic_mc,<span class="at">data=</span>data)</span>
<span id="cb381-4"><a href="solutions.html#cb381-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sim_slopes</span>(intrct_model, <span class="at">pred=</span>frame, <span class="at">modx=</span>skeptic_mc)</span></code></pre></div>
<pre><code>## JOHNSON-NEYMAN INTERVAL 
## 
## When skeptic_mc is OUTSIDE the interval [-2.21, 0.56], the slope of frame is p &lt; .05.
## 
## Note: The range of observed values of skeptic_mc is [-2.38, 5.62]
## 
## SIMPLE SLOPES ANALYSIS 
## 
## Slope of frame when skeptic_mc = -2.0327907438001187045984 (- 1 SD): 
## 
##    Est.   S.E.   t val.      p
## ------- ------ -------- ------
##   -0.29   0.16    -1.84   0.07
## 
## Slope of frame when skeptic_mc =  0.0000000000000001557469 (Mean): 
## 
##   Est.   S.E.   t val.      p
## ------ ------ -------- ------
##   0.12   0.11     1.05   0.30
## 
## Slope of frame when skeptic_mc =  2.0327907438001187045984 (+ 1 SD): 
## 
##   Est.   S.E.   t val.      p
## ------ ------ -------- ------
##   0.53   0.16     3.32   0.00</code></pre>
<p><strong>Evaluation:</strong> The results show that framing for participants who score low on climate change skepticism (here: -1 standard deviation from the mean, which is a score of X = -2.032) does not affect the strength of participants’ justifications for withdrawing aid for drought victims (<em>b</em> = -0.29, <em>p</em> = .07). However, the more extreme citizens’ climate change skepticism becomes, the more important the framing of the drought (as natural / climate change induced) becomes in determining how much participants justify withdrawal of aid for drought victims. For citizens that score average climate change skepticism (Mean = 0.000, <em>p</em> = .30), framing does still not affect justifications for withdrawal of aid. However, participants who score high on climate change skepticiism (here: +1 standard deviation from the mean, which is a score of X = +2.032) act differently based on framing of the disaster, i.e. their justification for withdrawal of aid increases (<em>b</em> = 0.53, <em>p</em> &lt; 001).</p>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb383-1"><a href="solutions.html#cb383-1" aria-hidden="true" tabindex="-1"></a><span class="fu">jnPlot</span>(intrct_model, <span class="at">pred=</span><span class="st">&quot;frame&quot;</span>, <span class="at">modx=</span><span class="st">&quot;skeptic_mc&quot;</span>, <span class="at">plot =</span> <span class="cn">FALSE</span>,<span class="at">mode=</span><span class="dv">1</span>,<span class="at">addEq=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## JOHNSON-NEYMAN INTERVAL 
## 
## When skeptic_mc is OUTSIDE the interval [-2.207, 0.556], the slope of frame is p &lt; .05.
## 
## Note: The range of observed values of skeptic_mc is [-2.378, 5.622]</code></pre>
<p><img src="CPA-Seminar_files/figure-html/unnamed-chunk-174-1.png" width="160%" /></p>
<p><strong>Evaluation:</strong> The plot shows that the frame effect on the strength of justifications for withdrawal of aid for drought victimrs turns insignificant for citizens who have a climate change score between -2.207 and 0.556. This means that for citizens who score very low on climate change skepticism and for citizens who score high on climate change skeptiicism, the strength of justifications for withdrawal of aid is dependent on framing of the disaster.</p>
</div>
<div id="task-6-7" class="section level3 unnumbered">
<h3>Task 6</h3>
<p><strong>Repeat the analysis using <code>processR</code> (i.e., the <code>process</code> function). Look only at the <code>processR</code> output and note down all the coefficients.</strong></p>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb385-1"><a href="solutions.html#cb385-1" aria-hidden="true" tabindex="-1"></a><span class="fu">process</span>(<span class="at">data=</span>data, <span class="at">y=</span><span class="st">&quot;justify&quot;</span>, <span class="at">x=</span><span class="st">&quot;frame&quot;</span>, <span class="at">w=</span><span class="st">&quot;skeptic_mc&quot;</span>,<span class="at">model=</span><span class="dv">1</span>,<span class="at">plot=</span><span class="dv">1</span>,<span class="at">seed=</span><span class="dv">123</span>)</span></code></pre></div>
<p><img src="images/Tut14_processR_3.JPG" /></p>

</div>
</div>
</div>












            </section>

          </div>
        </div>
      </div>
<a href="exercise-6-test-your-knowledge.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/LKobilke/CPA-Seminar/edit/main/index.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["CPA Seminar.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
